### ISSUE TITLE
Server crash on joining.

### ISSUE THREAD

**Issue by Nykiiee** [Electroblob77/Wizardry#221] opened 2019-08-26 03:42 UTC
Minecraft version: 1.12.2 
Wizardry version: 4.2.1 
Environment: Multiplayer Server (Roguelike Adventures and Dungeons 1.30a)

Issue details: I discovered a new runestone structure (ebwizardry:runestone@5) from this mod. it had a spider spawner in between with a chest below. I was hitting the spiders and it crashed the server. After that everytime i login to the server will proceed to crash the server. However my other friends who play on the server does not cause a server crash on login.

Link to crash report (if applicable): https://pastebin.com/4hi5nHQg

Update Temporary/Possible Fix : the only way for me to prevent the crash was to use NBT Explorer to search for the position of those spider entities under /world/region folder and delete them. This only worked because i have access to server files. 

Credit : https://youtu.be/fWUUsdp3pJ8 that helped me with temporary fix incase somebody needs this.

**Comment by SirAron111** [comment] 2019-08-26 16:24
It’s the Bug with revenge target. Until it’s fixed don’t set the config to not do revenge targeting for summons and it’s mostly hotfixed.

**Comment by Electroblob77** [comment] 2019-09-02 16:08
Duplicate of #188.

**Closed as completed by Electroblob77** 2019-09-02 16:08 UTC
Labels: bug, duplicate
