### ISSUE TITLE
[Feature request] Structures compatible with /locate

### ISSUE THREAD

**Issue by drghnio** [Electroblob77/Wizardry#703] opened 2021-08-02 16:35 UTC
there is no way of finding any Wizardry Structures with commands yet so why not adding the Structures to the /locate command?

**Comment by WinDanesz** [comment] 2021-08-27 09:53
The locate command only supports vanilla structures in 1.12.2

**Comment by WinDanesz** [comment] 2022-02-04 23:42
Duplicate of #6

**Closed as completed by WinDanesz** 2022-02-04 23:42 UTC
Labels: enhancement
