### ISSUE TITLE
inventory open crasj

### ISSUE THREAD

**Issue by theirryb** [Electroblob77/Wizardry#557] opened 2020-11-17 21:48 UTC
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.1 [change as necessary]
Environment: Singleplayer

Issue details: player rendering crash

Other mods involved: 

Link to crash report (if applicable): 
[crash-2020-11-17_16.28.40-client.txt](https://github.com/Electroblob77/Wizardry/files/5556374/crash-2020-11-17_16.28.40-client.txt)
[crash-2020-11-17_18.53.58-client.txt](https://github.com/Electroblob77/Wizardry/files/5556892/crash-2020-11-17_18.53.58-client.txt)

**Comment by Ghostrider231** [comment] 2020-11-17 22:15
The issue you're describing looks like a duplicate of issue https://github.com/Electroblob77/Wizardry/issues/556

**Comment by Electroblob77** [comment] 2020-12-04 18:31
Yes, it's a duplicate of #556 and #551.

**Closed as completed by Electroblob77** 2020-12-04 18:31 UTC
Labels: bug, duplicate
