### ISSUE TITLE
Crashing at launch

### ISSUE THREAD

**Issue by Dazeguy** [Electroblob77/Wizardry#342] opened 2020-01-20 19:04 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.7 
Environment: Server 

Issue details: My friend actually has everything installed except every time he tries to run Minecraft the mod crashes his launcher.

Other mods involved: Idk if any other mods are currently messing with this one exactly.

Link to crash report (if applicable): https://pastebin.com/ZJ7tXfV2

**Comment by Electroblob77** [comment] 2020-01-20 19:51
There's something very strange going on with your language setting. What language is your game set to?

**Comment by Dazeguy** [comment] 2020-01-20 20:06
Umm by language setting do you actually mean like language(English) or coding? I believe that my friend's language setting is set to English.

**Comment by Dazeguy** [comment] 2020-01-20 20:39
> There's something very strange going on with your language setting. What language is your game set to?
Umm by language setting do you actually mean like language(English) or coding? I believe that my friend's language setting is set to English.

**Comment by Electroblob77** [comment] 2020-01-20 22:48
Yes, I meant language as in English. For some reason, your game is crashing at the 1st loading phase (preInit) because something to do with the languages isn't initialised. Can you get your friend to try with just wizardry? This is almost certainly a compatibility problem since I've launched wizardry 4.2.7 with the exact forge version you're using without any problems, so it would be useful to verify that.

**Comment by Dazeguy** [comment] 2020-01-23 07:05
sorry it's taking a while he's been busy with life stuff and hasn't been able to boot up his pc

**Comment by Dazeguy** [comment] 2020-01-25 01:59
> Yes, I meant language as in English. For some reason, your game is crashing at the 1st loading phase (preInit) because something to do with the languages isn't initialised. Can you get your friend to try with just wizardry? This is almost certainly a compatibility problem since I've launched wizardry 4.2.7 with the exact forge version you're using without any problems, so it would be useful to verify that.

Alright I got him to try it without any of the other mods and here's the crash message.
https://pastebin.com/BXj0ySvt

**Comment by Tora-B** [comment] 2020-01-25 08:07
Your crash log is incomplete. Someone else has just posted a very similar issue (#344). What launcher are you using? Do you have your modpack in a separate instance or folder from the default vanilla location? Can you post your options.txt file?

**Comment by Electroblob77** [comment] 2020-01-25 17:10
Can you try it without antique atlas and baubles?

**Comment by Dazeguy** [comment] 2020-01-25 22:05
Here's the options txt.file https://pastebin.com/CzCmged8
Here's the crash log with no baubles or antique, https://pastebin.com/pwtc3SKR

Also yes he's put the other mods that we were using into a separate folder away from the .minecraft folder.

Launcher version he's on: "1.6.93"
He's had this problem where when he tries switches to the latest launcher it will crash on him.

**Comment by Dazeguy** [comment] 2020-01-29 17:26
Umm did this get closed?

**Comment by Electroblob77** [comment] 2020-01-29 23:04
No, the issue linked above did because it was a duplicate of this one, that's why it says closed there. This issue is still open.

**Comment by Dazeguy** [comment] 2020-02-04 23:07
Hmm any solutions as of yet?

**Comment by enjuto6565** [comment] 2020-03-15 18:05
Is there any solution to this issue?

**Comment by Electroblob77** [comment] 2021-01-17 18:13
This was fixed in 4.3.

**Closed as completed by Electroblob77** 2021-01-17 18:13 UTC
Labels: bug, crash, compatibility
