### ISSUE TITLE
[1.12.2] Unable to fill wand with mana using Tinkers Construct Crafting Table

### ISSUE THREAD

**Issue by Morpheus1101** [Electroblob77/Wizardry#107] opened 2019-01-13 03:54 UTC
Minecraft version: 1.12.2 
Wizardry version: 4.1.4 
Environment: Server

Issue details: Unable to refill mana of wand in Tinkers Crafting table. It breaks the wand giving it a large numberd negative durability as seen in the pic below

Other mods involved: Tinkers Construct

![2019-01-13_13 53 53](https://user-images.githubusercontent.com/10524952/51081414-bc86be80-173a-11e9-8989-5aaca212ab45.png)

**Comment by Electroblob77** [comment] 2019-01-14 23:11
Duplicate of #68, see that issue for the discussion.

**Closed as completed by Electroblob77** 2019-01-14 23:11 UTC
Labels: duplicate
