### ISSUE TITLE
Better Combat Rebirth Compatibility Issue

### ISSUE THREAD

**Issue by TheTrainwreck2010** [Electroblob77/Wizardry#177] opened 2019-08-18 22:35 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.0
Environment: Singleplayer/LAN game/Server 

Issue details: After updating Wizardry to 4.2.0, a crash happens anytime a mob is attacked while Better Combat Rebirth is enabled. This happens when using any item as a physical attack including fist and regardless of whether the items are being dual-wielded or not.

Other mods involved: Better Combat Rebirth 1.12.2-1.5.6

https://paste.dimdev.org/qatinoyafa.mccrash

**Comment by Electroblob77** [comment] 2019-08-19 10:18
Duplicate of #166. This has now been fixed in the 4.2.1 hotfix.

**Closed as completed by Electroblob77** 2019-08-19 10:18 UTC
Labels: bug, duplicate
