### ISSUE TITLE
Electroblob's Wizardy crashes on the latest build for 1.12.2

### ISSUE THREAD

**Issue by HenrikoMagnifico** [Electroblob77/Wizardry#505] opened 2020-09-27 20:58 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: Boot

Issue details: The game crashes when booting.

Other mods involved: See list of mods in the provided crash report.

Link to crash report (if applicable): https://hastebin.com/orijigexaf.rb

**Comment by Electroblob77** [comment] 2020-09-30 12:33
Duplicate of #342.

**Closed as completed by Electroblob77** 2020-09-30 12:33 UTC
Labels: bug, duplicate
