### ISSUE TITLE
RLcraft not compaitable

### ISSUE THREAD

**Issue by JYSG** [Electroblob77/Wizardry#731] opened 2021-10-28 15:47 UTC
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.4 [change as necessary]
Environment: Singleplayer
Issue details: [Playing the RLcraft mod pack with electrobob,able to cast spells with /cast but not able to add them on wands.

Other mods involved: RLcraft mods?

**Comment by WinDanesz** [comment] 2021-12-28 15:22
Cast commands are not supposed to add spells to wands, it just casts a spell

**Comment by ThatPoog** [comment] 2022-01-05 00:00
from what i can tell, its some error between Wizardry and lanse505's compat skills addon for the Reskillable mod. I'm far from having any idea of what I'm doing but since Wizardry isn't one of the mods listed in the compatibilities, it might be trying to read the Wizardry spells as Astral Sorcery spells and locking them behind nonexistent EXP requirements.

but hey thats just a game theory

**Comment by WinDanesz** [comment] 2022-01-05 13:34
> from what i can tell, its some error between Wizardry and lanse505's compat skills addon for the Reskillable mod. I'm far from having any idea of what I'm doing but since Wizardry isn't one of the mods listed in the compatibilities, it might be trying to read the Wizardry spells as Astral Sorcery spells and locking them behind nonexistent EXP requirements.
> 
> but hey thats just a game theory

AS and wizadry spells are fundamentally different (code), no way it could mix them up.

CompatSkills has support for Wizadry, but that support is known to cause more harm than good. Now I see what the original issue might have been about, this is a duplicate of #652 #609 

Go to compatskill's configs and disable the EbWiz support

**Closed as completed** 2022-02-03 12:39 UTC
Labels: bug, duplicate
