### ISSUE TITLE
World generation crash

### ISSUE THREAD

**Issue by LemADEC** [Electroblob77/Wizardry#3] opened 2018-02-07 23:54 UTC
Minecraft version: 1.10.2
Wizardry version: 2.1.0
Environment: Singleplayer

Issue details: flying around while generating the world

Other mods involved: none?

Link to crash report (if applicable):
```

java.lang.ArrayIndexOutOfBoundsException: 7
	at electroblob.wizardry.loot.RandomSpell.func_186553_a(RandomSpell.java:105)
	at net.minecraft.world.storage.loot.LootEntryItem.func_186363_a(LootEntryItem.java:36)
	at net.minecraft.world.storage.loot.LootPool.func_186452_a(LootPool.java:68)
	at net.minecraft.world.storage.loot.LootPool.func_186449_b(LootPool.java:83)
	at net.minecraft.world.storage.loot.LootTable.func_186462_a(LootTable.java:42)
	at net.minecraft.world.storage.loot.LootTable.func_186460_a(LootTable.java:57)
	at electroblob.wizardry.WizardryWorldGenerator.generateWizardTower(WizardryWorldGenerator.java:340)
	at electroblob.wizardry.WizardryWorldGenerator.generate(WizardryWorldGenerator.java:60)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_180495_p(World.java:842)
	at thaumcraft.common.world.ThaumcraftWorldGenerator.generateOres(ThaumcraftWorldGenerator.java:321)
	at thaumcraft.common.world.ThaumcraftWorldGenerator.generateAll(ThaumcraftWorldGenerator.java:347)
	at thaumcraft.common.world.ThaumcraftWorldGenerator.worldGeneration(ThaumcraftWorldGenerator.java:69)
	at thaumcraft.common.world.ThaumcraftWorldGenerator.generate(ThaumcraftWorldGenerator.java:57)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Electroblob77** [comment] 2018-02-08 13:46
Duplicate of curseforge issue #27 (don't worry, you weren't to know that!). I have now released Wizardry 2.1.1 which should fix this issue, let me know if it persists.

**Closed as completed by Electroblob77** 2018-02-08 13:46 UTC
Labels: bug, crash
