### ISSUE TITLE
Possession visual effect "leak"

### ISSUE THREAD

**Issue by FKasa** [Electroblob77/Wizardry#381] opened 2020-03-21 23:36 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.9
Environment: LAN game

Issue details: 
Possession makes friend playing with me on LAN get the same "possessed" filter/visual effect. The issue is it stays active on my friend even after I am done with it. It doesn't matter if the possessed mob is passive (squid) or aggressive (slime). Logout, login is a workaround for this issue.

Other mods involved: none relevant, using MC Eternal modpack.

**Comment by Tora-B** [comment] 2020-03-22 07:24
Duplicate of #179, which is fixed in the current release (4.2.10).

**Closed as completed** 2020-03-31 17:19 UTC
Labels: bug, duplicate
