### ISSUE TITLE
[Give a brief, relevant title here]

### ISSUE THREAD

**Issue by aycfes** [Electroblob77/Wizardry#224] opened 2019-08-29 16:13 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Singleplayer

Issue details: an ice wizard used ice spikes on me

Other mods involved: none that i know
[crash-2019-08-29_13.06.53-server.txt](https://github.com/Electroblob77/Wizardry/files/3556484/crash-2019-08-29_13.06.53-server.txt)

**Comment by Ghostrider231** [comment] 2019-08-29 18:46
Your crash log is pretty much exactly like my crash report.

Rest of info here:
https://github.com/Electroblob77/Wizardry/issues/188

**Comment by Electroblob77** [comment] 2019-09-02 16:31
Can confirm this is a duplicate of #188.

**Closed as completed by Electroblob77** 2019-09-02 16:31 UTC
Labels: bug, duplicate
