### ISSUE TITLE
No Such Method Error Crashes Minecraft Modpack Loading

### ISSUE THREAD

**Issue by pyroAvatar91** [Electroblob77/Wizardry#663] opened 2021-05-20 16:45 UTC
Minecraft version: 1.12.2
Wizardry version: 4.3.4 
Environment: Singleplayer 

Issue details: When initializing minecraft, the game crashes halfway through phase 2 and gives me a "no such method" error that is related to this mod. I am pretty sure this is the same issue as mentioned in #640, however I have the most updated version of both this mod and Arcane Essentials and the game still crashes with the same error.

Other mods involved: Please See Pastebin for full list (200+ mods)

Here's my crash log: https://pastebin.com/buCS1eFi

Thanks for any help you can provide!

**Comment by WinDanesz** [comment] 2021-05-20 19:46
duplicate of #640
You must use the **alpha** version (which is under the beta category, huh), that is the latest version of that addon. Also this doesn't really concern EBWiz, addon issues should be raised at the addon Issue trackers.
latest alpha: https://www.curseforge.com/minecraft/mc-mods/arcane-essentials/files/3205508

**Comment by pyroAvatar91** [comment] 2021-05-21 04:44
Thank you! I appreciate your help and patience as I'm sure you've seen this a lot. I'm still a bit new to modpacks but will know in the future to always check for alpha versions that don't automatically download. Thanks again!

**Comment by WinDanesz** [comment] 2021-05-21 07:40
No probs, if it works, please close the issue

**Closed as completed** 2021-06-14 11:09 UTC
Labels: invalid
