### ISSUE TITLE
Arcane workbench button does nothing when the latest CompatSkills is installed [see latest comment for solution!]

### ISSUE THREAD

**Issue by davebob007** [Electroblob77/Wizardry#609] opened 2021-01-24 14:41 UTC
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.3.3 
Environment: Singleplayer

Issue details: when i place the wand in the arcane work bench with crystals and a spell book and hit the check mark it makes the animation and sound but nothing happens to the wand

Other mods involved: im running with rlcraft

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by FlowerGunn** [comment] 2021-01-24 22:23
Hey there. This is the same issue as #592 and #593 .

Backstory:
So @Electroblob77 noticed that the problem is in mod CompatSkills, so he suggested going back on the Wizardry version, or asking CompatSkills dev/devs to update the mod. Unfortunately, CompatSkills was not updated since 2019. I looked at their [changelog](https://github.com/Coders-After-Dark/CompatSkills/blob/master/CHANGELOG.MD#1163) and noticed that they added a lock for arcane workbench when using locked books or wand upgrades for example. And it was their latest update 1.17 . 

Solutions:
1. Downgrade Wizardry down to 4.2.x and miss out on all current and later Wizardry content.
2. Downgrade CompatSkills to 1.16.x and miss out on arcane workbench locks.

P.s. I tested downgrading CompatSkills and both mods **SEEM** to work properly.

**Comment by Electroblob77** [comment] 2021-01-30 17:40
Thanks for that explanation @RomanAndrosiuk, that is indeed correct. Closing this since there's nothing I can do about it, but I'll pin the issue so hopefully the workaround is visible for people.

**Closed as completed by Electroblob77** 2021-01-30 17:40 UTC
Labels: bug, duplicate, compatibility, workaround exists, external bug

**Comment by EthanLightning** [comment] 2021-03-06 19:34
If found an easy solution to this. In your Minecraft folder, you go to config and open up the CompatSkills document. In it, there's a list of mods with either true or false next to them. By setting Electroblobs wizardry to false CompatSkills will ignore it and you don't have to change anything else.

**Comment by Chartjer** [comment] 2021-06-18 13:34
![4165](https://user-images.githubusercontent.com/85975602/122569038-8ae55080-d074-11eb-8065-47debab6abcc.jpg)

**Comment by Chartjer** [comment] 2021-06-18 13:35
should i set anything to false?

**Comment by Electroblob77** [comment] 2021-06-24 22:10
Yes, set `ebwizardry` to false.

**Comment by diacreep14** [comment] 2021-07-03 17:03
Hello. I play the KN Mythic Novus Modpack on the official Multiplayer Server and i have the same issue as mentions here with one exception, this Modpack doesn't have CompatSkills as an mod and other players can use the mod. I can also use the mod in Singleplayer but not in Multiplayer which is kinda frustrating... Please help

**Comment by Electroblob77** [comment] 2021-07-03 18:03
See #634. If you have any new information then please comment on that issue since this one is closed.
