### ISSUE TITLE
[ArrayIndexOutOfBoundsException: -1]

### ISSUE THREAD

**Issue by Misoss** [Electroblob77/Wizardry#300] opened 2019-11-02 11:34 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.2
Environment: Client

At each connection to the server we have an error message

`java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at electroblob.wizardry.client.ClientProxy.handleGlyphDataPacket(ClientProxy.java:548)
    at electroblob.wizardry.packet.PacketGlyphData.lambda$onMessage$0(PacketGlyphData.java:26)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:529)`

Thank you for your help

**Comment by shadinx2** [comment] 2019-11-09 10:33
https://paste.dimdev.org/everatigud.mccrash

**Comment by shadinx2** [comment] 2019-11-09 10:33
Same or very similar problem. Happens when I press ctrl i.

**Comment by Electroblob77** [comment] 2019-11-16 15:20
Duplicate of #253. This is a bug in arcane essentials 0.9.2.

**Closed as completed by Electroblob77** 2019-11-16 15:20 UTC
Labels: bug, duplicate
