### ISSUE TITLE
Game crash when I enter other mod’s world

### ISSUE THREAD

**Issue by CloudMeow** [Electroblob77/Wizardry#564] opened 2020-12-04 07:42 UTC
Minecraft version: 1.12.2
Wizardry version: 4.3.1
Environment: Singleplayer

Issue details:  When I enter the dimension of Pontus (the dimension from Harshen Universe Mod)，my game crash，and the reason is about Electroblob's Wizardry mod

Other mods involved: Harshen Universe Mod

Link to crash report (if applicable): 
[crash-2020-11-28_18.12.05-server.txt](https://github.com/Electroblob77/Wizardry/files/5641163/crash-2020-11-28_18.12.05-server.txt)

**Comment by brisingraerowing** [comment] 2020-12-04 17:16
It appears that VillageNames is trying to set an Evil Wizard's NBT before said wizard is fully loaded.

**Comment by Electroblob77** [comment] 2020-12-04 18:14
Duplicate of #491.

**Closed as completed by Electroblob77** 2020-12-04 18:14 UTC
Labels: bug, duplicate
