### ISSUE TITLE
can not bind spell and upgrade wand [Give a brief, relevant title here]

### ISSUE THREAD

**Issue by Ixanr2** [Electroblob77/Wizardry#593] opened 2021-01-01 09:09 UTC
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.1 [change as necessary]
Environment: Singleplayer/LAN game/Server [delete as necessary]

Issue details: I can't bind spells using my arcane workbench i have installed the mod in RLCRAFT please help

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by Electroblob77** [comment] 2021-01-01 11:50
Duplicate of #592.

**Closed as completed by Electroblob77** 2021-01-01 11:50 UTC
Labels: bug, duplicate
