### ISSUE TITLE
Crash report when loading mod in new modpack

### ISSUE THREAD

**Issue by TyrusJames** [Electroblob77/Wizardry#375] opened 2020-03-09 22:25 UTC
Crash report with new modpack I'm making, called out your mod. Perhaps a conflict?

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2020-03-09 21:52:53 GMT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:418)
    at java.util.ArrayList.get(ArrayList.java:431)
    at electroblob.wizardry.client.ClientProxy.handleGlyphDataPacket(ClientProxy.java:558)
    at electroblob.wizardry.packet.PacketGlyphData.lambda$onMessage$0(PacketGlyphData.java:26)
    at electroblob.wizardry.packet.PacketGlyphData$$Lambda$3355/1013438701.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2249979368 bytes (2145 MB) / 4088397824 bytes (3899 MB) up to 7658274816 bytes (7303 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8216m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 96 mods loaded, 96 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                       | Version                  | Source                                             | Signature                                |
       |:------ |:------------------------ |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                | 1.12.2                   | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                      | 9.42                     | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                      | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCHIJA | forge                    | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCHIJA | openmodscore             | 0.12.2                   | minecraft.jar                                      | None                                     |
       | LCHIJA | foamfixcore              | 7.7.4                    | minecraft.jar                                      | None                                     |
       | LCHIJA | jei                      | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                          | None                                     |
       | LCHIJA | abyssalcraft             | 1.9.16                   | AbyssalCraft-1.12.2-1.9.16.jar                     | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | mantle                   | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCHIJA | ctm                      | MC1.12.2-1.0.1.30        | CTM-MC1.12.2-1.0.1.30.jar                          | None                                     |
       | LCHIJA | twilightforest           | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
       | LCHIJA | tconstruct               | 1.12.2-2.13.0.179        | TConstruct-1.12.2-2.13.0.179.jar                   | None                                     |
       | LCHIJA | acintegration            | 1.9.0                    | AbyssalCraft Integration-1.12.2-1.9.0.jar          | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | aether_legacy            | 1.4.4                    | aether_legacy-1.12.2-v1.4.4.jar                    | None                                     |
       | LCHIJA | ambientsounds            | 3.0                      | AmbientSounds_v3.0.9_mc1.12.2.jar                  | None                                     |
       | LCHIJA | ebwizardry               | 4.2.9                    | ElectroblobsWizardry-4.2.9-MC1.12.2.jar            | None                                     |
       | LCHIJA | ancientspellcraft        | 1.0.1                    | AncientSpellcraft-1.12.2-1.0.1.jar                 | None                                     |
       | LCHIJA | codechickenlib           | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | ancientwarfare           | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
       | LCHIJA | ancientwarfarestructure  | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
       | LCHIJA | ancientwarfarevehicle    | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
       | LCHIJA | ancientwarfarenpc        | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
       | LCHIJA | redstoneflux             | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | ancientwarfareautomation | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
       | LCHIJA | appleskin                | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | LCHIJA | arcane_essentials        | 1.0                      | Arcane Essentials-0.9.2.jar                        | None                                     |
       | LCHIJA | baubles                  | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHIJA | baubleshud               | 5.0.2                    | BaublesHud-1.12.2-5.0.2.jar                        | None                                     |
       | LCHIJA | betteradvancements       | 0.1.0.77                 | BetterAdvancements-1.12.2-0.1.0.77.jar             | None                                     |
       | LCHIJA | patchouli                | 1.0-20                   | Patchouli-1.0-20.jar                               | None                                     |
       | LCHIJA | bewitchment              | 0.21.10                  | bewitchment-1.12.2-0.0.21.10.jar                   | None                                     |
       | LCHIJA | bibliocraft              | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
       | LCHIJA | guideapi                 | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
       | LCHIJA | bloodmagic               | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105.jar                    | None                                     |
       | LCHIJA | bloodmoon                | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | crafttweaker             | 4.1.20                   | CraftTweaker2-1.12-4.1.20.jar                      | None                                     |
       | LCHIJA | conarm                   | 1.2.5.4                  | conarm-1.12.2-1.2.5.4.jar                          | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | bloodtinker              | 1.0.5                    | bloodtinker-1.0.5.jar                              | None                                     |
       | LCHIJA | bookshelf                | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | botania                  | r1.10-363                | Botania r1.10-363.jar                              | None                                     |
       | LCHIJA | hammercore               | 2.0.6.13                 | HammerCore-1.12.2-2.0.6.13.jar                     | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | botanicadds              | 4r                       | BotanicAdditions-1.12.2-4r.jar                     | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | nibbler                  | 0.4.1                    | nibbler-1.12.2-0.4.1.jar                           | None                                     |
       | LCHIJA | botaunomy                | 0.2.1                    | botaunomy-1.12.2-0.2.1.jar                         | None                                     |
       | LCHIJA | brandonscore             | 2.4.18                   | BrandonsCore-1.12.2-2.4.18.210-universal.jar       | None                                     |
       | LCHIJA | chameleon                | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | LCHIJA | chickenchunks            | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | chunkanimator            | 1.2                      | ChunkAnimator-MC1.12-1.2.jar                       | None                                     |
       | LCHIJA | clumps                   | 3.1.2                    | Clumps-3.1.2.jar                                   | None                                     |
       | LCHIJA | controlling              | 3.0.8                    | Controlling-3.0.8.jar                              | None                                     |
       | LCHIJA | ctgui                    | 1.0.0                    | CraftTweaker2-1.12-4.1.20.jar                      | None                                     |
       | LCHIJA | crafttweakerjei          | 2.0.3                    | CraftTweaker2-1.12-4.1.20.jar                      | None                                     |
       | LCHIJA | cucumber                 | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
       | LCHIJA | draconicevolution        | 2.3.25                   | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
       | LCHIJA | draconicadditions        | 1.11.0                   | Draconic-Additions-1.12.2-1.11.0.31-universal.jar  | None                                     |
       | LCHIJA | enderstorage             | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | waila                    | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | LCHIJA | extrabotany              | 58                       | ExtraBotany-r1.1-58r.jar                           | None                                     |
       | LCHIJA | extra_spells             | 1.1.4                    | ExtraSpells-1.12.2-1.1.4.jar                       | None                                     |
       | LCHIJA | extrautils2              | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
       | LCHIJA | fastleafdecay            | v14                      | FastLeafDecay-v14.jar                              | None                                     |
       | LCHIJA | floocraftft              | 1.9.6                    | Floocraft 1.12.2-1.9.6.jar                         | None                                     |
       | LCHIJA | foamfix                  | 0.10.10-1.12.2           | foamfix-0.10.10-1.12.2.jar                         | None                                     |
       | LCHIJA | huntingdim               | 1.0.42                   | HuntingDimension-1.12.2-1.0.42.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | llibrary                 | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire               | 1.8.4                    | iceandfire-1.8.4.jar                               | None                                     |
       | LCHIJA | infernalmobs             | 1.7.6                    | InfernalMobs-1.12.2.jar                            | None                                     |
       | LCHIJA | infinitic                | 1.12.2-0.1.46            | Infini-TiC-1.12.2-0.1.46.jar                       | None                                     |
       | LCHIJA | inventorytweaks          | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironchest                | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
       | LCHIJA | journeymap               | 1.12.2-5.7.0             | journeymap-1.12.2-5.7.0.jar                        | None                                     |
       | LCHIJA | jeresources              | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
       | LCHIJA | lost_aether              | 0.1.2                    | lost_aether-content-1.12.2-0.1.2.jar               | None                                     |
       | LCHIJA | morpheus                 | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                        | None                                     |
       | LCHIJA | mousetweaks              | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
       | LCHIJA | mysticalagriculture      | 1.7.5                    | MysticalAgriculture-1.12.2-1.7.5.jar               | None                                     |
       | LCHIJA | mysticalagradditions     | 1.3.2                    | MysticalAgradditions-1.12.2-1.3.2.jar              | None                                     |
       | LCHIJA | openmods                 | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | openblocks               | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | plustic                  | 7.1.6.1                  | plustic-7.1.6.1.jar                                | None                                     |
       | LCHIJA | roguelike                | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
       | LCHIJA | t3s4ebw                  | 1.0                      | SeedsForWizardry 1.0 For MC Forge 1.12.2.jar       | None                                     |
       | LCHIJA | stg                      | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                               | None                                     |
       | LCHIJA | storagedrawers           | 1.12.2-5.4.1             | StorageDrawers-1.12.2-5.4.1.jar                    | None                                     |
       | LCHIJA | tfspellpack              | 1.0                      | TFSpellPack-1.0-MC1.12.2.jar                       | None                                     |
       | LCHIJA | tinkersaether            | 1.3.0                    | tinkersaether-1.3.0.jar                            | None                                     |
       | LCHIJA | tcomplement              | 1.12.2-0.4.3             | TinkersComplement-1.12.2-0.4.3.jar                 | None                                     |
       | LCHIJA | tinkerscompendium        | 1.4.2.33                 | tinkersdefense-1.4.2.33.jar                        | None                                     |
       | LCHIJA | tinkersjei               | 1.2                      | tinkersjei-1.2.jar                                 | None                                     |
       | LCHIJA | tinkertoolleveling       | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
       | LCHIJA | tombstone                | 3.6.8                    | tombstone-3.6.8-1.12.2.jar                         | None                                     |
       | LCHIJA | vanillafix               | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                           | None                                     |
       | LCHIJA | wawla                    | 2.6.274                  | Wawla-1.12.2-2.6.274.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | wrd                      | 0.8.0                    | Wesley's Roguelike Dungeons V0.8.1.jar             | None                                     |
       | LCHIJA | immersiveengineering     | 0.12-92                  | ImmersiveEngineering-0.12-92.jar                   | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCHIJA | phosphor-lighting        | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar        | f0387d288626cc2d937daa504e74af570c52a2f1 |
  Loaded coremods (and transformers): CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      HCASM (HammerCore-1.12.2-2.0.6.13.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.10.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      iceandfire (iceandfire-1.8.4.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4749' Renderer: 'Intel(R) HD Graphics 530'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  HammerCore Debug Information: Dependent Mods:
                                    -Botanic Additions (botanicadds) @4r
  Pulsar/tcomplement loaded Pulses: - ModuleCommons (Enabled/Forced)
                                    - ModuleMelter (Enabled/Not Forced)
                                    - ModuleArmor (Enabled/Not Forced)
                                    - ModuleSteelworks (Enabled/Not Forced)
                                    - ToolLevelingPlugin (Enabled/Not Forced)
                                    - Oredict (Enabled/Forced)
  Suspected Mods: Electroblob's Wizardry (ebwizardry)

**Comment by Electroblob77** [comment] 2020-03-15 17:48
Duplicate of #253. Update arcane essentials to the newest version.

**Closed as completed by Electroblob77** 2020-03-15 17:48 UTC
Labels: bug, duplicate
