### ISSUE TITLE
Losing spellbooks in the Arcane Workbench

### ISSUE THREAD

**Issue by smoothuk** [Electroblob77/Wizardry#385] opened 2020-03-23 15:09 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.10
Environment: Singleplayer

Issue details: If an arcane workbench contains a wand and spellbooks and you remove the wand while your inventory is full, the spellbooks magically disappear, forever.  *POOF*

**Comment by Electroblob77** [comment] 2020-03-31 18:01
They should be dropped on the floor. I have tested this on a clean install with just wizardry and can confirm that the books are dropped on the floor as intended. Do you have some sort of auto-pickup device that's stashing the items away somewhere, or even voiding them?

**Comment by smoothuk** [comment] 2020-03-31 19:11
Nope, am not using any auto-pickup or anything like that.  I too would expect the books to drop to the floor.  I do have around 100 mods in my pack though, so I'll do some more testing to see if i figure anything else out.

**Comment by smoothuk** [comment] 2020-03-31 19:44
Ok either I'm going crazy or the bug fixed itself.  I can't reproduce it either.  I guess you can close this issue, but it it happens again I'll be sure to report it.

**Comment by Electroblob77** [comment] 2020-03-31 20:09
Hmmm, weird... I'll close this for now, but please reopen it (or make a new issue and mention this one) if this happens again.

**Closed as completed by Electroblob77** 2020-03-31 20:09 UTC
Labels: bug, can't reproduce
