### ISSUE TITLE
Crash when throwing Lightning Hammer

### ISSUE THREAD

**Issue by Kutzeee** [Electroblob77/Wizardry#194] opened 2019-08-20 18:24 UTC
Minecraft version: 1.12.2 
Wizardry version: 4.2.1

Issue details: Throwing the Lightning Hammer causes the game to crash
https://paste.dimdev.org/uzodarehib.mccrash

**Comment by Electroblob77** [comment] 2019-08-20 19:08
Duplicate of #191.

**Closed as completed by Electroblob77** 2019-08-20 19:08 UTC
Labels: bug, duplicate
