### ISSUE TITLE
Wizardry crashing with Dynamic trees upon world gen. 

### ISSUE THREAD

**Issue by RetroNomad** [Electroblob77/Wizardry#265] opened 2019-09-27 18:28 UTC
**Minecraft version:** 1.12.2   
**Wizardry version:** 4.2.3
**Environment:** Single player for mod pack testing before moving it to a live environment

**Issue details:** While testing a modified pack I seem to be getting a crash related to EBWizardry attempting to remove Dynamic trees Dynamic leaves when generating structures (If I'm reading the CR correctly) I can confirm that Forge has been tested with 5 different versions, 4 being the most recent and the 5th being the suggested when attempting to load the mod with anything lower than required. forge......5.2815 I believe.  Upon removing EBWizardry and dependent mods  the world is free to instantly load with all versions tested prior and no changes made to anything else

**Other mods involved:** BOP compliant Dynamic trees

**Link to crash report :** https://pastebin.com/LZ8D8t6W

**Comment by Electroblob77** [comment] 2019-09-27 22:03
Duplicate of #186, the workaround is to enable fast worldgen in wizardry's config for the time being.

**Closed as completed by Electroblob77** 2019-09-27 22:03 UTC
Labels: bug, duplicate
