### ISSUE TITLE
Crash when opening inventory

### ISSUE THREAD

**Issue by APonche97** [Electroblob77/Wizardry#556] opened 2020-11-16 21:02 UTC
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.1 [change as necessary]
Environment: Singleplayer

Issue details: [describe what you were doing when the issue occurred, what went wrong, what you expected to happen, etc.]

Other mods involved: micdoodle8.mods.galacticraft

Link to crash report (if applicable): 

Description: Rendering entity in world

java.lang.NullPointerException
    at electroblob.wizardry.client.animation.PlayerAnimator.onRenderPlayerPostEvent(PlayerAnimator.java:234)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1005_PlayerAnimator_onRenderPlayerPostEvent_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.client.renderer.entity.RenderPlayer.doRender(RenderPlayer.java:74)
    at net.minecraft.client.renderer.entity.RenderPlayer.doRender(RenderPlayer.java:28)
    at net.minecraft.client.renderer.entity.RenderManager.renderEntity(RenderManager.java:384)
    at net.minecraft.client.gui.inventory.GuiInventory.drawEntityOnScreen(SourceFile:128)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawGuiContainerBackgroundLayer(GuiContainerCreative.java:802)
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:75)
    at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:51)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:643)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being rendered --
  Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP)
  Entity ID: 27841
  Entity Name: TheBlueBlade
  Entity's Exact location: 63.12, 65.00, 630.59
  Entity's Block location: World: (63,65,630), Chunk: (at 15,4,6 in 3,39; contains blocks 48,0,624 to 63,255,639), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null

**Comment by jasperfirecai2** [comment] 2020-11-28 15:30
Can confirm this issue happens when opening inventory if galacticraft is installed

**Comment by Electroblob77** [comment] 2020-12-04 19:08
Duplicate of #551.

**Closed as completed** 2020-12-04 19:18 UTC
Labels: bug, duplicate
