### ISSUE TITLE
Arcane Wizardry sorcery install spell book error

### ISSUE THREAD

**Issue by ghost** [Electroblob77/Wizardry#722] opened 2021-10-02 14:07 UTC
Minecraft version: 1.12.2
Wizardry version: 4.3.4 
Environment: Server

Issue details: I was at the arcane workbench trying to install the spell book for my staff, but when I clicked "Install" there was an error in the background and the staff failed to install the spell

Link to crash report (if applicable): https://paste.ubuntu.com/p/HpqJM3SN9q/

**Comment by WinDanesz** [comment] 2021-10-02 15:32
Looks like the "Compatskills" mod causes it, not wizardry

**Comment by WinDanesz** [comment] 2022-02-03 13:09
duplicate of #609

**Closed as completed by WinDanesz** 2022-02-03 13:09 UTC
Labels: duplicate, workaround exists, external bug
