### ISSUE TITLE
Game crashes while search JEI because of Evil Wizard.

### ISSUE THREAD

**Issue by PliskintheSaltyFork** [Electroblob77/Wizardry#575] opened 2020-12-14 04:44 UTC
Minecraft version: 1.12.2 
Wizardry version: 4.3.1
Environment: Singleplayer

Issue details: I've been working on a personal modpack for Minecraft 1.12.2.  Electroblob's Wizardry crashes my game when searching JEI, because of the Evil Wizard.  VanillaFix seems to think it has to with Electroblob's Wizardry, Village Names, and DrZhark's CustomSpawner.

Crash Report: https://pastebin.com/yh34u36n

Anyone help to at least get a workaround for this would be great.  I don't want to axe this mod from the back.

**Comment by brisingraerowing** [comment] 2020-12-14 18:44
The event VillageNames uses to set entity names fires before full initialization for some mobs, resulting in null values that cause crashes. Also, this is a duplicate of #491 .

**Comment by Electroblob77** [comment] 2020-12-15 18:18
Yep, duplicate of #491.

**Closed as completed by Electroblob77** 2020-12-15 18:18 UTC
Labels: bug, duplicate
