### ISSUE TITLE
Quality tools compatibility

### ISSUE THREAD

**Issue by Another-human51** [Electroblob77/Wizardry#425] opened 2020-04-25 07:10 UTC
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: Singleplayer/LAN game

The potioncore.magicDamage property only affects some spells while the projectileDamage affect others and the support ones like healing cant be modified at all 
EDIT:
looks like someone already reported it

**Comment by Electroblob77** [comment] 2020-05-06 11:39
Yes, this is a duplicate of #396.

**Closed as completed by Electroblob77** 2020-05-06 11:39 UTC
Labels: bug, duplicate
