### ISSUE TITLE
Mobs get glitch when get shot in 3rd person view

### ISSUE THREAD

**Issue by ming2318** [Electroblob77/Wizardry#536] opened 2020-10-30 15:29 UTC
Minecraft version: 1.12.2
Wizardry version: 4.3
Environment: Singleplayer and Server

Issue details: When I get shot by arrow in 3rd person view , the other mobs will being upside down and displacement
![glitch](https://user-images.githubusercontent.com/73707777/97724281-b0364600-1b07-11eb-83d8-f6ff699e85e0.png)

Other mods involved: Optifine
Link to crash report: 
![log](https://user-images.githubusercontent.com/73707777/97724325-baf0db00-1b07-11eb-899e-1f33d3cbf996.png)

**Comment by Electroblob77** [comment] 2020-10-30 15:46
Duplicate of #529.

**Closed as completed by Electroblob77** 2020-10-30 15:46 UTC
Labels: bug, duplicate
