### ISSUE TITLE
Bookshelf eating too much RAM

### ISSUE THREAD

**Issue by GodMorduk** [Electroblob77/Wizardry#621] opened 2021-02-04 03:58 UTC
Minecraft version: 1.12.2 
Wizardry version: 4.3.4
Environment: Singleplayer

Issue details: bookshelf model eating 32mb of retained heap and got a lot of int[] objects. It is much for a single block, entire mod takes ~40mb of memory, so it doesn't seems as it should be. 

Other mods involved: nothing I can identify. I don't place bookshelf in world, its just straight after loading heap dump.

![image](https://user-images.githubusercontent.com/22483969/106842857-d85cb480-66b5-11eb-9115-a5edb40289a1.png)

Not sure I'm getting it correctly, but it seems that somehow it stores all possible book variants in memory? My Java skills are not appropriate for such problem, but hope it somehow helps.

![image](https://user-images.githubusercontent.com/22483969/106843365-ebbc4f80-66b6-11eb-8c8a-dbaaf21bdd83.png)

**Comment by Electroblob77** [comment] 2021-02-07 14:01
Interesting, I can't say I've noticed a performance impact. I notice that each `BakedModelBookshelf` has a different object assigned to its `books` field, I can't remember if this was intended but it shouldn't be necessary since all bookshelves share the same book models. Multiply this by 6 wood variants and 4 orientations and that's a lot of book models!

Here is the code that bakes the bookshelf models:

https://github.com/Electroblob77/Wizardry/blob/32340191de0c338e0f375b5b919fed98cf6f04f0/src/main/java/electroblob/wizardry/client/model/ModelBookshelf.java#L48-L68

It may be that I mistakenly assumed that `IModel#bake(...)` retrieves the existing baked model if it already exists, when in fact it must be making a new one each time that code is called (once for each bookshelf and orientation). I will see if there is a method for retrieving existing baked models instead, that might work.

**Comment by GodMorduk** [comment] 2021-02-08 07:05
Maybe an config option to create only one "generic" bookshelf (or turn off some) would also help. I don't think everyone needs 6 variants, so there would be only 4, not 24 models. 

Also why do you have a model for each direction? As I've seen, blockstates can handle it.

**Comment by Electroblob77** [comment] 2021-02-11 16:08
> Maybe an config option to create only one "generic" bookshelf (or turn off some) would also help. I don't think everyone needs 6 variants, so there would be only 4, not 24 models.

There is no reason why the game can't handle an arbitrary number of bookshelf types without much performance impact if done correctly. I would much rather fix the root cause of the problem rather than cover it up by removing features.

> Also why do you have a model for each direction? As I've seen, blockstates can handle it.

I don't. There is only one model _file_ for each bookshelf type, but the way the model system works is it _generates_ one 'baked' model for each blockstate when the game loads. That's what all those objects are in the screenshot you posted.

Anyway, the point is not that there are too many bookshelf models, the problem is that it seems to be creating separate baked models for the _books_ (not the bookshelf) in each type of bookshelf even though they are always the same. I just need to make it reuse the book models it has already generated.

**Closed as completed** 2022-02-01 18:25 UTC
Labels: bug, performance
