### ISSUE TITLE
Stone of Transporation Crash

### ISSUE THREAD

**Issue by voidswrath** [Electroblob77/Wizardry#339] opened 2020-01-15 18:39 UTC
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version:ElectroblobsWizardry-4.2.5-MC1.12.2
Environment: Server 

Issue details: When an already bound circle is right clicked with a wand for a 2nd time. It crashes client not server.

Other mods involved: [only list mods that are relevant to the problem]
optifine
ebwizardy

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]
https://pastebin.com/XeTDJUJA

**Comment by Electroblob77** [comment] 2020-01-16 18:29
Duplicate of #307. This was fixed in wizardry 4.2.6, please update to the latest version (currently 4.2.7).

**Closed as completed by Electroblob77** 2020-01-16 18:29 UTC
Labels: bug, duplicate
