### ISSUE TITLE
crash when pressing f5

### ISSUE THREAD

**Issue by mk1213123** [Electroblob77/Wizardry#555] opened 2020-11-16 15:43 UTC
Minecraft version: 1.12.2
Wizardry version: 4.3.1
Environment: Singleplayer
Issue details: [when pressing f5 to change the view it crash 

Link to crash report (if applicable):https://pastebin.pl/view/a0be2370

**Comment by Electroblob77** [comment] 2020-12-04 19:12
Duplicate of #551.

**Closed as completed by Electroblob77** 2020-12-04 19:12 UTC
Labels: bug, duplicate
