### ISSUE TITLE
Spell Crashing PLayer

### ISSUE THREAD

**Issue by Orokah** [Electroblob77/Wizardry#416] opened 2020-04-19 03:34 UTC
Using the Ice Chariet crashes the player and says server chunk error.

Using the possession on any nonvanilla monsters causes a server chunk error and crashes the player.

Mod Pack: MC Launcher.

Sadly have no idea how to get a crash report since it's not crashing on the server, but individual players. We've also tried having various players of 32ram, rtx2080 pcs try and run the spells and they have the same issue.

**Comment by Electroblob77** [comment] 2020-04-20 10:28
Chariot of ice is a spell from the twilight forest spell pack, it's a known issue though I am currently unable to reproduce it.

You'll need to ask the player that crashed to give you their crash report (find the crash_reports folder and grab the newest file in there). Without it I can't help you, sorry.

**Comment by Electroblob77** [comment] 2020-09-12 12:57
This has been fixed in TF Spell Pack 1.0.2.

**Closed as completed by Electroblob77** 2020-09-12 12:57 UTC
Labels: bug, crash, insufficient detail
