### ISSUE TITLE
Mod Crash On Start Up

### ISSUE THREAD

**Issue by lPhazonl** [Electroblob77/Wizardry#34] opened 2018-05-13 07:19 UTC
Minecraft version: **1.12.2** 
Wizardry version: **2.1.1** 
Forge version: **14.23.1.2555**
Environment: **Singleplayer**

Issue details: Once I add the mod into the Mod folder and attempt to run the game it would always crash on start up. It used to leave a crash log but now it no longer does. I had someone else give me their working version of the mod but it still crashes. _I'l add the crash log if that helps unless you're looking for something else I am welcome to comply._

Mod: **Electroblob's Wizardry**

Link to crash report (if applicable):---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  llibrary (LLibrary-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 5/13/18 12:10 AM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraftforge.registries.IForgeRegistry.getValuesCollection()Ljava/util/Collection;
	at electroblob.wizardry.spell.Spell.getTotalSpellCount(Spell.java:374)
	at electroblob.wizardry.item.ItemSpellBook.func_150895_a(ItemSpellBook.java:42)
	at electroblob.wizardry.client.model.WizardryItemModels.registerItemModel(WizardryItemModels.java:177)
	at electroblob.wizardry.client.model.WizardryItemModels.register(WizardryItemModels.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_38_WizardryItemModels_register_ModelRegistryEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.client.FMLClientHandler.fireSidedRegistryEvents(FMLClientHandler.java:1095)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireSidedRegistryEvents(FMLCommonHandler.java:757)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at electroblob.wizardry.spell.Spell.getTotalSpellCount(Spell.java:374)
	at electroblob.wizardry.item.ItemSpellBook.func_150895_a(ItemSpellBook.java:42)
	at electroblob.wizardry.client.model.WizardryItemModels.registerItemModel(WizardryItemModels.java:177)
	at electroblob.wizardry.client.model.WizardryItemModels.register(WizardryItemModels.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_38_WizardryItemModels_register_ModelRegistryEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.client.FMLClientHandler.fireSidedRegistryEvents(FMLClientHandler.java:1095)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireSidedRegistryEvents(FMLCommonHandler.java:757)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1127729904 bytes (1075 MB) / 1744830464 bytes (1664 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version              | Source                                                 | Signature                                |
	|:----- |:----------------- |:-------------------- |:------------------------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft         | 1.12.2               | minecraft.jar                                          | None                                     |
	| UCH   | mcp               | 9.42                 | minecraft.jar                                          | None                                     |
	| UCH   | FML               | 8.0.99.99            | forge-1.12.2-14.23.1.2555.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge             | 14.23.1.2555         | forge-1.12.2-14.23.1.2555.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | mercurius_updater | 1.0                  | MercuriusUpdater-1.12.2.jar                            | None                                     |
	| UCH   | aquaculture       | 1.6.1                | Aquaculture-Mod-1.12.2.jar                             | None                                     |
	| UCH   | biomesoplenty     | 7.0.1.2302           | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar          | None                                     |
	| UCH   | bloodmoon         | 1.5.1                | Bloodmoon-MC1.12-1.5.1.jar                             | None                                     |
	| UCH   | cw                | 1.0.1                | Creature-Whisperer-Mod-1.12.2.jar                      | None                                     |
	| UCH   | customspawner     | 3.11.3               | CustomMobSpawner-3.11.3.jar                            | None                                     |
	| UCH   | dldungeonsjdg     | 1.11.1               | DoomlikeDungeons-1.11.1-MC1.12.2.jar                   | None                                     |
	| UCH   | mocreatures       | 12.0.3               | DrZharks MoCreatures Mod-12.0.3.jar                    | None                                     |
	| UCE   | ebwizardry        | 4.1.1                | Electroblob's+Wizardry+-+4.1.1+-+MC+1.12.2 (1).jar     | None                                     |
	| UCH   | enhanced_snowman  | 1.0                  | Enhanced-Snowman-Mod-1.12.2.jar                        | None                                     |
	| UCH   | erebus            | 1.0.22               | Erebus-1.0.22.jar                                      | None                                     |
	| UCH   | gargoyles         | 1                    | Gargoyles-Mod-1.12.2.jar                               | None                                     |
	| UCH   | gravestone        | 1.0.13               | GraveStone-1.12-Graves-1.0.13.jar                      | None                                     |
	| UCH   | astikoor          | 1.0.0                | Horse-Carts-Mod-1.12.2.jar                             | None                                     |
	| UCH   | llibrary          | 1.7.7                | LLibrary-1.12.2.jar                                    | None                                     |
	| UCH   | iceandfire        | 1.3.1                | Ice-and-Fire-Mod-1.12.2.jar                            | None                                     |
	| UCH   | melongolem        | 1.0.1                | Melon-Golem-Mod-1.12.2.jar                             | None                                     |
	| UCH   | overlord          | 2.4.10               | Overlord-1.12.2-2.4.10.jar                             | None                                     |
	| UCH   | rotd              | 1.0                  | Realm+Of+The+Dragons+1.12.2+(TheRPGAdventurer)-1.0.jar | None                                     |
	| UCH   | roguelike         | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar                     | None                                     |
	| UCH   | spartanweaponry   | beta 1.1.2           | SpartanWeaponry-1.12.2-beta-1.1.2.jar                  | None                                     |
	| UCH   | toroquest         | 1.12.2-5.2           | toroquest-1.12.2-5.2.jar                               | None                                     |
	| UCH   | twilightforest    | 3.5.263              | twilightforest-1.12.2-3.5.263-universal.jar            | None                                     |
	| UCH   | waddles           | 0.5.6                | Waddles-Mod-1.12.2.jar                                 | None                                     |
	| UCH   | thejungle         | 1.011.1222           | Welcome-to-the-Jungle-Mod-1.12.2.jar                   | None                                     |
	| UCH   | wolfarmor         | 1.12.2-2.1.0-RELEASE | Wolf-Armor-Storage-Mod-1.12.2.jar                      | None                                     |
	| UCH   | xlfoodmod         | 1.12.2-1.3.0         | XL-Food-Mod-1.12.2.jar                                 | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
llibrary (LLibrary-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 397.64' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2555
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 397.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: John Smith Legacy 1.12.2 v5.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz

**Comment by Electroblob77** [comment] 2018-05-13 09:41
Duplicate of #28. This is also in the FAQs on curseforge and the minecraft forum thread, please read them before posting an issue. To fix it, please update your forge to build 2611 or newer.

(In future please use gist or pastebin for crash reports.)

**Closed as completed by Electroblob77** 2018-05-13 09:41 UTC
Labels: duplicate
