### ISSUE TITLE
Crashes on sound events. (Including mob sounds and going into sounds menu)

### ISSUE THREAD

**Issue by Stormister** [Electroblob77/Wizardry#220] opened 2019-08-26 00:01 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Singleplayer

Issue details: Any time I fight any mobs from this mod, or go into the sound settings in the options menu, the game gives me the error shown in the crash report. I am assuming these events are all linked, given that it returns the same error in all cases. This happens with or without Optifine, so I know that is not the culprit.

Other mods involved: IC2, maybe, since it adds a volume slider? But I am updated to the latest version of IC2 as of today, so I'm not totally sure that's the case. I unfortunately don't have the time right now to test all of my mods to see which is the culprit, so I will return when I do get the chance to do further testing.

Link to crash report (if applicable): https://paste.dimdev.org/ufocepeyof.mccrash

**Comment by kreezxil** [comment] 2019-08-26 14:07
confirmed we have this same problem, one of our players can't log on to the server because of it.

players client report: https://paste.dimdev.org/titeriqoci.mccrash

**Comment by SirAron111** [comment] 2019-08-26 16:30
This is the bug with the sound in ebwiz currently it’s incompatible with any mod that tries to normally access sound in any way. Since ebwiz currently has a bug that’s causes it to mess up settings for sound and so on. (If you just play with eb wiz you can see that in the form of you changing the spell sound volume and on the next log in the settings for sound reset themselves.) Only fix is to always delete the options.txt before launching the game it’s not really a fix just prevents the crash in the instance for a while. Here is more information https://github.com/Electroblob77/Wizardry/issues/217

**Comment by kreezxil** [comment] 2019-08-26 17:55
That's a horrible solution. Need to point out that I have tons of players reporting this issue now. It's literally a problem with the latest EBWIZARDY. I'll be rolling back to the previous version to fix it.

**Comment by Stormister** [comment] 2019-08-30 12:16
> That's a horrible solution. Need to point out that I have tons of players reporting this issue now. It's literally a problem with the latest EBWIZARDY. I'll be rolling back to the previous version to fix it.

Does a previous version not have this issue? If so, which one? I'd like to still use this mod but with a major crash like this I cant justify adding it

**Comment by kreezxil** [comment] 2019-08-30 23:47
Matthew, correct version 1.12.2-4.1.4 does not have this problem.

**Comment by Electroblob77** [comment] 2019-09-02 16:06
Can confirm this is a duplicate of #198.

**Closed as completed by Electroblob77** 2019-09-02 16:06 UTC
Labels: bug, duplicate
