### ISSUE TITLE
Galacticraft and EBWizardry Causing Game to Crash

### ISSUE THREAD

**Issue by DragonArtsV** [Electroblob77/Wizardry#532] opened 2020-10-28 18:41 UTC
Minecraft version: 1.12.2 
Wizardry version: 4.3 
Environment: Singleplayer

Issue details: I made a modpack and it crashed so I removed mods and added them back slowly, finding EBWizardry and Galacticraft to be the problem. Minecraft would load up fine until you entered a world. When the world would sit at a black screen before crashing completely giving me:
(The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
Exit Code: -1)
and the crash report
(https://pastebin.com/MU6S1ugj)
Both load fine on their own.
Other mods involved: Galacticraft Core, Galacticraft Planets MicdoodleCore

**Comment by DragonArtsV** [comment] 2020-10-28 18:46
After some testing to make sure every other mod worked Morph has the same issue.
(https://pastebin.com/iFzWMwhA)
Edit: only crashes when morphing/ loading into a world morphed may be related as its turning the same error

**Comment by Electroblob77** [comment] 2020-10-28 23:16
Duplicate of #518.

**Closed as completed by Electroblob77** 2020-10-28 23:16 UTC
Labels: bug, duplicate
