### ISSUE TITLE
Client crash on casting any spell

### ISSUE THREAD

**Issue by JWTHDYTWA** [Electroblob77/Wizardry#191] opened 2019-08-20 08:14 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Singleplayer

java.lang.ArrayIndexOutOfBoundsException
Any casted spell causes minecraft to crash. Crash itself is being avoided when there's Vanilla Fix installed, therefore minecraft just freezes for a moment. Some spells cause to involve Random Things into crashlog.

Other mods involved: Random Things, Vanilla Fix

Link to crash report: [[→1←]](https://gist.github.com/Warrock3280/c1a287a68e73271d7edd4e335935e4fe), [[→2←]](https://gist.github.com/Warrock3280/d498002cd42dd904853daba64810b4d7)

**Comment by Electroblob77** [comment] 2019-08-20 09:41
Looks like something to do with the spells sound category. Could you list any mods you have installed which do something to the sounds? Thanks.

**Comment by BeardStroker** [comment] 2019-08-20 15:25
I am having a similar issue, but during my troubleshooting I found a even stranger one. 
After getting this crash:

java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException

I suspected that a mod called Dynamic Surroundings which affects sounds were involved. Muting individual sounds via that mod did nothing, but when I pressed the "Music and sounds" option in the pause menu just to test if muting the game would do anything, suddenly the game crashed to the main menu and I got this crash:

java.lang.ArrayIndexOutOfBoundsException


-- Affected screen --
  Screen name: org.orecruncher.dsurround.client.gui.GuiScreenOptionsSoundReplace

So yeah, I think dynamic surroundings might be involved. Warrock do you have that mod installed?

**Comment by Electroblob77** [comment] 2019-08-20 17:08
I suspect the issue is a conflict between how dynamic surroundings adds its sound categories and how wizardry adds its one. Strangely though, I actually have dynamic surroundings installed myself and it's running fine alongside wizardry.

Could you try going into your options.txt and pasting the lines that start with `soundCategory` here?

**Comment by WenXin20** [comment] 2019-08-20 17:17
I have noticed the same issue, but I do not have Dynamic Surroundings, but I do have Random Things installed.
Edit: [Crash Report](https://paste.dimdev.org/mamaqamupa.mccrash)
        [Full Log](https://gist.github.com/WenXin20/e42f2df4a4bf65510db893ace3ce1470)

**Comment by Electroblob77** [comment] 2019-08-20 17:25
Interesting, Random Things does not add any sound categories as far as I can tell. Could you post your crash report? It may not be the same issue at all.

I can tell from the crash reports that Warrock does have dynamic surroundings.

**Comment by WenXin20** [comment] 2019-08-20 17:27
Just added it to the above post.
Edit: The crash report doesn't mention Random Things, but the full log does.
I also just noticed that the full log has two reports in it, one mentions Random Things, the other doesn't.

**Comment by BeardStroker** [comment] 2019-08-20 17:33
I'll post the lines from options.txt when I get back to my computer, but just wanted to mention that I too have random things installed, and an earlier crash from the version before this one mentioned that mod when it crashed as I punched the lightning hammer. I did test that with the current version and could not recreate it.

**Comment by Electroblob77** [comment] 2019-08-20 19:10
I think the involvement of Random Things is probably a coincidence, it doesn't seem to be related to the crash itself.

**Comment by SirAron111** [comment] 2019-08-20 19:40
I think whatever causes you to be unable to adjust sound values also removes the effect sounds from spells.

**Comment by BeardStroker** [comment] 2019-08-21 12:33
Here are the lines starting with soundCategory from the options.txt file:

soundCategory_master:0.29801324
soundCategory_music:0.23239437
soundCategory_record:1.0
soundCategory_weather:1.0
soundCategory_block:1.0
soundCategory_hostile:1.0
soundCategory_neutral:1.0
soundCategory_player:1.0
soundCategory_ambient:1.0
soundCategory_voice:1.0
soundCategory_ds_footsteps:1.0
soundCategory_ds_biome:1.0

**Comment by JWTHDYTWA** [comment] 2019-08-21 13:02
Here's some new crash reports. [This one is when i tried to shift-rightclick `Greater Telekinesis Scroll` on chest.](https://gist.github.com/Warrock3280/f760129d8a7c7b630b0d5530fc0797fb) [The second is chained from previous crash.](https://gist.github.com/Warrock3280/815ee08efe99695ff2a5799e48397b1c) [Then endless crash loop in main menu (thanks to vanilla fix)...](https://gist.github.com/Warrock3280/b3ee9a5567649bff1430efacaf6cbbb8)

Btw, talking of sounds, Random Things has sound muffling mechanics. `Sound Dampener`s and such.

**Comment by BeardStroker** [comment] 2019-08-21 14:19
I did some more testing, removing random things changed nothing, same crashes, but when I removed dynamic surroundings and kept random things I did actually still crash. https://gist.github.com/BeardStroker/e56e3fb7683213fb4ba5b83e389dc998

And it also still crashes when pressing the music and sounds option button.
https://gist.github.com/BeardStroker/5a8bdfc82cee8ec96b75b8594f5f8d87

I'll test removing both
Edit: Still crashes with both random things and Dynamic Surroundings removed, sooo I'm stumped
https://gist.github.com/BeardStroker/23ab00f178ecfda840b25fe1bcf968cb

**Comment by ElfYamada** [comment] 2019-08-21 17:32
Same thing has been happening to me, but only in a server. Whenever I use a spell - if im in the area where the spell was cast - I get kicked from the game with the same error code. However, If I use a spell and i'm not in its aoe then it works just fine? very strange :// 

Works just fine in single player though

**Comment by ddd800** [comment] 2019-08-22 05:15
Same problem as everyone else however just kicks the player from the server and they can just rejoin. I also happen to use random things in the pack,

**Comment by LemADEC** [comment] 2019-08-22 06:34
Issue is intermittent and can be reproduced without randomthings.
I've also noticed the 'Spells' sound category doesn't always shows up in the options menu.

**Comment by ValentineBlaze** [comment] 2019-08-22 20:43
im having a similar problem when it comes to sounds in all the mods I have in, I have the midnight and wizardry and both seem to be having this problem. anything I can do as a fix myself?

**Comment by ValentineBlaze** [comment] 2019-08-23 01:32
Now i dont think wizardry is the cause of the problems since i had it with midnight before i added wizardry but more of just the sound library causing the problems if i read through these things properly. However even if thats the case i am still unsure about why thats causing the music and sounds to crash whenever you try opening it to well change individual volumes of things

**Comment by WenXin20** [comment] 2019-08-23 02:15
That's interesting, I don't have Midnight installed and only had this problem after adding Wizardry.

**Comment by ValentineBlaze** [comment] 2019-08-23 04:19
the problem did get worse after adding wizardry. but I did notice it having the problem too. side question how do I find the sound cache of things

**Comment by ValentineBlaze** [comment] 2019-08-23 05:59
okay so doing my own testing and I disabled wizardry and I am able to access my sound menu again, as well had a crash on a mp server and heres the crash log 
(I am also so sorry about all the problems happening)
https://paste.dimdev.org/ludizinobi.mccrash  I think my midnight problems are something different so ignore me on that side of things, also electrobob I am willing to send you my mudpack if you want it for trying to find the problem. its just a private pack for me and my friends.

**Comment by LemADEC** [comment] 2019-08-23 08:14
Issue is intermittent and can be reproduced without randomthings, without mightnight, without wizardry.

**Comment by Pengu-Hunter** [comment] 2019-08-23 08:33
Possible workaround, I've got the same issue but making a new profile and transferring config, mods And saves folders to the new profile and the problem doesn't happen, might produce different results for others.
Edit: Don't transfer the saves folder, you need to make a new save.

**Comment by ddd800** [comment] 2019-08-24 00:08
After comparing all these different crash reports, these are all the mods that all the reports on here share.
https://hastebin.com/awaqoxusaj.rb

**Comment by KamiSami** [comment] 2019-08-25 13:11
I hope to see fix to this soon, i really do not want to remove this mod from of the server, as this bug is causing way too much issues...

**Comment by ddd800** [comment] 2019-08-30 01:57
Roll it back to a previous version. Didnt hurt our server but you may run across missing texture spell books.

**Comment by Electroblob77** [comment] 2019-09-04 12:14
Missed this, it's actually yet another duplicate of #198 (or rather, #198 is a duplicate of this one).

**Closed as completed by Electroblob77** 2019-09-04 12:14 UTC
Labels: bug, crash, compatibility
