### ISSUE TITLE
Summon Spirit Horse Broken

### ISSUE THREAD

**Issue by MountainWulf** [Electroblob77/Wizardry#163] opened 2019-08-10 02:36 UTC
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: Singleplayer

Issue details: Summon Spirit Horse no longer works. It's one of my most used spells but today it just wouldn't do anything. The last I remember using my horse, I had jumped through a portal to a new dimension and left it behind. I suspect that it never despawned. Now, I figure if I go back, it would despawn after ten seconds and everything would be fine... But I no longer have that dimension, it's been deleted and I can't get it back and I have no way to ever get there again. I read on here an issue like this one and someone said to use NBT Editor to set hasSpiritHorse value from 1 to 0. I tried that, but every time I restart Minecraft, it resets to 1. I also tried the command to cast the spell but it just says it's unable to do that.

**Comment by Electroblob77** [comment] 2019-08-11 09:32
Duplicate of #74, see the discussion there.

**Closed as completed by Electroblob77** 2019-08-11 09:32 UTC
Labels: bug, duplicate

**Comment by MountainWulf** [comment] 2019-08-11 19:03
I know it's like 74, I mentioned it in my post. But the fix listed there does not work for me. Do you know of another way for me to try to get my horse back?

**Comment by Electroblob77** [comment] 2019-08-11 19:21
> I know it's like 74, I mentioned it in my post.

So you did... I should read things properly, sorry! Not sure why that fix wouldn't work for you, unfortunately I don't know of another way to do it. You could try quitting Minecraft before editing the world data if you didn't do that last time.

This bug will be fixed in the 4.2 release very soon so if all else fails you won't have long to wait.

**Comment by MountainWulf** [comment] 2019-08-11 19:32
I tried with Minecraft off, on and anything else I could think of. I guess he's just going to be gone for a while. Sad, but I needed to walk anyways. My character was getting lazy. Thanks for the help.
