### ISSUE TITLE
Still crashing with dynamic trees

### ISSUE THREAD

**Issue by EightBlade** [Electroblob77/Wizardry#186] opened 2019-08-19 14:52 UTC
Minecraft version: 1.12.2 
Wizardry version: 4.2.1
Environment: Singleplayer

Issue details: Still getting a conflict, not sure why. Forge is latest as is Dynamic Trees.

Other mods involved: Dynamic Trees

https://pastebin.com/YMZbgHHw

**Comment by Electroblob77** [comment] 2019-08-19 18:07
Are you using fast structure generation?

**Comment by EightBlade** [comment] 2019-08-19 18:09
Nope, I have that set to False.

**Comment by ethanccss** [comment] 2019-08-20 02:50
I'm facing the same problem. Same setup, same versions. Crashes after a few mins of play with dynamic trees being the conflict.

**Comment by Electroblob77** [comment] 2019-08-20 10:02
Dynamic trees is incompatible with fancy structure generation at the moment, it seems dynamic trees doesn't like its leaves being ticked when there's no tree to support them. The 4.2.1 update doesn't fix this problem, but it does mean that fast structure generation won't generate stuff on top of dynamic trees.

**Comment by ethanccss** [comment] 2019-08-20 16:03
Thank you for the information. Hopefully this can be fixed in future releases as dynamic trees is a must to avoid ugly world gen. Awesome mod and awesome work, keep it up!

**Comment by ethanccss** [comment] 2019-08-20 16:03
> Dynamic trees is incompatible with fancy structure generation at the moment, it seems dynamic trees doesn't like its leaves being ticked when there's no tree to support them. The 4.2.1 update doesn't fix this problem, but it does mean that fast structure generation won't generate stuff on top of dynamic trees.

Thank you for the information. Hopefully this can be fixed in future releases as dynamic trees is a must to avoid ugly world gen. Awesome mod and awesome work, keep it up!

**Comment by EightBlade** [comment] 2019-08-20 20:03
What's the workaround? Enabling fast world gen?

**Comment by mgcgian** [comment] 2019-08-31 17:34
any workarpund?

**Comment by Electroblob77** [comment] 2019-09-02 16:33
Yes, enable fast worldgen.

**Comment by Glendening** [comment] 2019-09-10 00:40
Was this also reported to the dynamic trees github? I'm not seeing a reference there though I could just be missing it.

**Comment by Electroblob77** [comment] 2019-09-10 11:17
Not that I know of. You can report it there if you like, the problem is that dynamic trees' leaves don't like being ticked when they aren't attached to any logs.

**Closed as completed** 2019-10-05 14:35 UTC
Labels: bug, crash, compatibility, workaround exists
