### ISSUE TITLE
Game crashes with world gen

### ISSUE THREAD

**Issue by mgcgian** [Electroblob77/Wizardry#227] opened 2019-08-31 17:03 UTC
Game crashes with worldgen  says unknown source i think it conflicts with dynamic trees.
heres the crashlog

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.4.0.BETA.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  ColytraLoadingPlugin (Colytra-Mod-1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 8/31/19 3:33 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.ferreusveritas.dynamictrees.blocks.BlockDynamicLeaves.func_180650_b(BlockDynamicLeaves.java:122)
	at electroblob.wizardry.worldgen.WorldGenSurfaceStructure.lambda$removeFloatingTrees$0(WorldGenSurfaceStructure.java:357)
	at electroblob.wizardry.worldgen.WorldGenSurfaceStructure$$Lambda$2186/1972564543.accept(Unknown Source)
	at java.util.ArrayList.forEach(Unknown Source)
	at electroblob.wizardry.worldgen.WorldGenSurfaceStructure.removeFloatingTrees(WorldGenSurfaceStructure.java:357)
	at electroblob.wizardry.worldgen.WorldGenSurfaceStructure.generate(WorldGenSurfaceStructure.java:247)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.ChunkCache.<init>(ChunkCache.java:37)
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:113)
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:65)
	at net.minecraft.pathfinding.PathNavigate.func_75488_a(SourceFile:93)
	at net.minecraft.pathfinding.PathNavigate.func_75492_a(SourceFile:143)
	at net.minecraft.entity.ai.EntityAIWander.func_75249_e(SourceFile:65)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:223)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.ferreusveritas.dynamictrees.blocks.BlockDynamicLeaves.func_180650_b(BlockDynamicLeaves.java:122)
	at electroblob.wizardry.worldgen.WorldGenSurfaceStructure.lambda$removeFloatingTrees$0(WorldGenSurfaceStructure.java:357)
	at electroblob.wizardry.worldgen.WorldGenSurfaceStructure$$Lambda$2186/1972564543.accept(Unknown Source)
	at java.util.ArrayList.forEach(Unknown Source)
	at electroblob.wizardry.worldgen.WorldGenSurfaceStructure.removeFloatingTrees(WorldGenSurfaceStructure.java:357)
	at electroblob.wizardry.worldgen.WorldGenSurfaceStructure.generate(WorldGenSurfaceStructure.java:247)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.ChunkCache.<init>(ChunkCache.java:37)
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:113)
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:65)
	at net.minecraft.pathfinding.PathNavigate.func_75488_a(SourceFile:93)
	at net.minecraft.pathfinding.PathNavigate.func_75492_a(SourceFile:143)
	at net.minecraft.entity.ai.EntityAIWander.func_75249_e(SourceFile:65)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:223)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: minecraft:zombie (net.minecraft.entity.monster.EntityZombie)
	Entity ID: 9284
	Entity Name: Zombie
	Entity's Exact location: -1249.50, 31.00, -1412.50
	Entity's Block location: World: (-1250,31,-1413), Chunk: (at 14,1,11 in -79,-89; contains blocks -1264,0,-1424 to -1249,255,-1409), Region: (-3,-3; contains chunks -96,-96 to -65,-65, blocks -1536,0,-1536 to -1025,255,-1025)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: The Land Of OOO
	All players: 1 total; [EntityPlayerMP['mgcgian'/7717, l='The Land Of OOO', x=-1160.26, y=55.21, z=-1446.53]]
	Chunk stats: ServerChunkCache: 560 Drop: 0
	Level seed: 1280036128918655258
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (8,64,-60), Chunk: (at 8,4,4 in 0,-4; contains blocks 0,0,-64 to 15,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1187706 game time, 1504025 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 96947 (now: false), thunder time: 52790 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 712909600 bytes (679 MB) / 1765830656 bytes (1684 MB) up to 2725511168 bytes (2599 MB)
	JVM Flags: 4 total; -Xmn128M -Xmx2612M -XX:+UseConcMarkSweepGC -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 73 mods loaded, 73 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version                  | Source                                        | Signature                                |
	|:------ |:-------------------------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                                          | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                        | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                 | None                                     |
	| LCHIJA | foamfixcore                                  | 7.7.4                    | minecraft.jar                                 | None                                     |
	| LCHIJA | dsurroundcore                                | 3.5.4.3                  | minecraft.jar                                 | None                                     |
	| LCHIJA | aether_legacy                                | 1.4.4                    | aether_legacy-1.12.2-v1.4.4.jar               | None                                     |
	| LCHIJA | infinitylib                                  | 1.12.2-1.12.0            | InfinityLib-1.12.2.jar                        | None                                     |
	| LCHIJA | agricraft                                    | 2.12.0-1.12.0-a6         | AgriCraft-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | animalium                                    | 0.3.8                    | Animalium-0.3.8.jar                           | None                                     |
	| LCHIJA | baubles                                      | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | bettercombatmod                              | 1.5.6                    | BetterCombat-1.12.2-1.5.6.jar                 | None                                     |
	| LCHIJA | biomesoplenty                                | 7.0.1.2439               | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar | None                                     |
	| LCHIJA | better_diving                                | 1.3.91                   | BetterDiving-1.12.2-1.3.91.jar                | None                                     |
	| LCHIJA | bibliocraft                                  | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
	| LCHIJA | buildcraftlib                                | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcraftcore                               | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcraftbuilders                           | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcrafttransport                          | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcraftsilicon                            | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcraftcompat                             | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcraftenergy                             | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcraftfactory                            | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcraftrobotics                           | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | colytra                                      | 1.2.0.3                  | Colytra-Mod-1.12.2.jar                        | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | coralreef                                    | 2.0                      | Coral-Reef-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | cosmiclib                                    | 0.4.0                    | CosmicLib-1.12.2-0.4.0.BETA.jar               | d3974446c00f9f1d275edce305771eeddf30c658 |
	| LCHIJA | customspawner                                | 3.11.4                   | Custom-Mob-Spawner-Mod-1.12.2.jar             | None                                     |
	| LCHIJA | movingworld                                  | 1.12-6.342               | movingworld-1.12-6.342-full.jar               | None                                     |
	| LCHIJA | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar           | None                                     |
	| LCHIJA | dynamictrees                                 | 1.12.2-0.9.5             | DynamicTrees-1.12.2-0.9.5.jar                 | None                                     |
	| LCHIJA | dynamictreesbop                              | 1.12.2-1.4.1e            | DynamicTreesBOP-1.12.2-1.4.1e.jar             | None                                     |
	| LCHIJA | ebwizardry                                   | 4.2.1                    | ElectroblobsWizardry-4.2.1-MC1.12.2.jar       | None                                     |
	| LCHIJA | exoticbirds                                  | 1.0                      | Exotic+Birds+1.12.2-2.2.1.jar                 | None                                     |
	| LCHIJA | foamfix                                      | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                     | None                                     |
	| LCHIJA | llibrary                                     | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil                                       | 8.0.2                    | fossilsarcheology-8.0.2.jar                   | None                                     |
	| LCHIJA | iceandfire                                   | 1.7.0                    | Ice-and-Fire-Mod-1.12.2.jar                   | None                                     |
	| LCHIJA | ichunutil                                    | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest                                    | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCHIJA | journeymap                                   | 1.12.2-5.5.5b7           | JourneyMap-Mod-1.12.2-Unlimited.jar           | None                                     |
	| LCHIJA | jaff                                         | 1.7_for_1.12             | Just-a-Few-Fish-Mod-1.12.jar                  | None                                     |
	| LCHIJA | lostcities                                   | 2.0.21                   | lostcities-1.12-2.0.21.jar                    | None                                     |
	| LCHIJA | millenaire                                   | Millénaire 7.2.1         | millenaire-1.12.2-7.2.1.jar                   | None                                     |
	| LCHIJA | radixcore                                    | 1.12.x-2.2.1             | RadixCore-1.12.2.jar                          | None                                     |
	| LCHIJA | mca                                          | 1.12.2-5.3.1             | Minecraft-Comes-Alive-Mod-1.12.2.jar          | None                                     |
	| LCHIJA | mobarmormod                                  | 1.0.3b                   | Mob+Armor+Mod+V1.0.3b-1.12.2.jar              | None                                     |
	| LCHIJA | mocreatures                                  | 12.0.5                   | MoCreatures.jar                               | None                                     |
	| LCHIJA | mowziesmobs                                  | 1.5.3                    | Mowzies-Mobs-Mod-1.12.2.jar                   | None                                     |
	| LCHIJA | cfm                                          | 6.3.1                    | MrCrayfishs-Furniture-Mod-1.12.2.jar          | None                                     |
	| LCHIJA | mysticalwildlife                             | 1.3.0.1                  | mysticalwildlife-1.12.2-1.3.0.1.jar           | None                                     |
	| LCHIJA | harvestcraft                                 | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2ze.jar               | None                                     |
	| LCHIJA | placebo                                      | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                      | None                                     |
	| LCHIJA | plants2                                      | 2.10.7                   | Plants-1.12.2-2.10.7.jar                      | None                                     |
	| LCHIJA | portalgun                                    | 7.1.0                    | PortalGun-1.12.2-7.1.0.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | roughmobs                                    | 2.0.0                    | roughmobs2-1.12.2_2.0.15.jar                  | None                                     |
	| LCHIJA | sereneseasons                                | 1.2.16                   | SereneSeasons-1.12.2-1.2.16-universal.jar     | None                                     |
	| LCHIJA | flammpfeil.slashblade                        | mc1.12-r28               | SlashBlade-mc1.12-r28.jar                     | None                                     |
	| LCHIJA | spartanshields                               | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar               | None                                     |
	| LCHIJA | thirdpersonelytra                            | 1.0                      | ThirdPersonElytra-1.12.2v1.0.jar              
| None                                     |
	| LCHIJA | toxicrain                                    | 2.0.0                    | ToxicRain-1.12.2-2.0.0.jar                    | None                                     |
	| LCHIJA | xat                                          | 0.25.2                   | Trinkets+and+Baubles-1.12.2-0.25.2.jar        | None                                     |
	| LCHIJA | uteamcore                                    | 2.2.4.107                | u_team_core-1.12.2-2.2.4.107.jar              | None                                     |
	| LCHIJA | usefulbackpacks                              | 1.5.1.35                 | useful_backpacks-1.12.2-1.5.1.35.jar          | None                                     |
	| LCHIJA | vanilladeathchest                            | 1.12.2-1.9.3.0           | vanilladeathchest-1.12.2-1.9.3.0.jar          | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
	| LCHIJA | wawla                                        | 2.5.273                  | Wawla-1.12.2-2.5.273.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | wolfarmor                                    | 2.2.3.6                  | Wolf-Armor-Storage-Mod-1.12.2.jar             | None                                     |
	| LCHIJA | aquatic                                      | 1.0.0-c                  | Aquatic-1.12.2-1.0.0-c.jar                    | 7b14aaee2dd17b12a140baecab28948fff3a263f |
	| LCHIJA | orelib                                       | 3.5.2.2                  | OreLib-1.12.2-3.5.2.2.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround                                    | 3.5.4.3                  | DynamicSurroundings-1.12.2-3.5.4.3.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.4.0.BETA.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ColytraLoadingPlugin (Colytra-Mod-1.12.2.jar)
  c4.colytra.asm.ElytraTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)  
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['mgcgian'/7717, l='The Land Of OOO', x=-1160.26, y=55.21, z=-1446.53]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by mgcgian** [comment] 2019-08-31 17:07
this is whenever a building from the mod spawns

**Comment by Electroblob77** [comment] 2019-09-02 16:34
Duplicate of #186. For now, the workaround is to enable fast worldgen.

**Closed as completed by Electroblob77** 2019-09-02 16:34 UTC
Labels: bug, duplicate
