### ISSUE TITLE
Could lead up to crash or corruption in the future. Maybe.

### ISSUE THREAD

**Issue by MasonBlood9696** [Electroblob77/Wizardry#361] opened 2020-02-18 12:06 UTC
Hello there. So my game told me that the mod could lead up to some consequences, such as crash, corruption and etc. I have the latest version of this mod. Could you please take a look of this link?

https://paste.dimdev.org/uyokuzizod.mccrash

Many thanks!

**Comment by Tora-B** [comment] 2020-02-19 11:49
Duplicate of #253. This is a bug in Arcane Essentials, which may be fixed in the latest beta version.

**Closed as completed** 2020-02-19 14:48 UTC
Labels: bug
