### ISSUE TITLE
Problem when a new world is made

### ISSUE THREAD

**Issue by Severynn99** [Electroblob77/Wizardry#356] opened 2020-02-09 10:27 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.8
Environment: Singleplayer

Issue details: I started a new world and instantly at the top right of my screen it said there was a potential problem found. Not sure what it's about but I got the report. It says this mod is a potential cause of the problem

Other mods involved: I play with 126 mods but it only says this one's the problem

Link to crash report (if applicable): https://paste.dimdev.org/isonifebil.mccrash

**Comment by Electroblob77** [comment] 2020-02-09 13:32
Duplicate of #253. This was a bug in the arcane essentials addon, FavouriteDragon just released an alpha build which fixes this issue so try updating to that and it should resolve the issue.

**Closed as completed by Electroblob77** 2020-02-09 13:32 UTC
Labels: bug, duplicate
