### ISSUE TITLE
Vanilla fix alerts me of an error.

### ISSUE THREAD

**Issue by soupcant95** [Electroblob77/Wizardry#350] opened 2020-02-01 18:41 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.8
Environment: Singleplayer

Issue details: Nothing went wrong. I just loaded my singleplayer mod and a vanillafix popup alerted me of an error. I just wanted to send this to you all so you can find bugs :) 

Other mods involved: Wizardry

Link to crash report: https://paste.dimdev.org/fipilexiye.mccrash

**Comment by Electroblob77** [comment] 2020-02-05 20:18
Duplicate of #253. This is a bug in the arcane essentials addon.

**Closed as completed by Electroblob77** 2020-02-05 20:18 UTC
Labels: bug, duplicate
