### ISSUE TITLE
Crashes after using some spells

### ISSUE THREAD

**Issue by JakobRaiden** [Electroblob77/Wizardry#223] opened 2019-08-28 00:43 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Privately hosted server

My game crashes after using many different spells. My friend playing with the same pack on the same server doesn't have the same issue. The issue also wasn't present for the entire day and olny started after a server restart.

https://pastebin.com/YuFvhBEq

also only happens in survival. In creative mode it all works perfectly fine.

**Comment by JakobRaiden** [comment] 2019-08-28 00:45
The affected spells tested so far are greater firebolt, summon lightning wraith, and an undiscovered spell when I tried to use it for discovery.

**Comment by Electroblob77** [comment] 2019-09-02 16:30
Duplicate of #183.

**Closed as completed by Electroblob77** 2019-09-02 16:30 UTC
Labels: bug, duplicate
