### ISSUE TITLE
Crash with DoubleSlabs

### ISSUE THREAD

**Issue by ALJ323** [Electroblob77/Wizardry#542] opened 2020-11-04 09:24 UTC
Minecraft version: 1.12.2
Wizardry version: 4.3.1
Environment: Singleplayer/LAN game/Server

Issue details: Game crashes with Double Slabs on load at step 3/7 with both Wizardry 4.3 and 4.3.1, prior versions work.

Other mods involved: Double Slabs v0.7.3

Link to crash report (if applicable): https://paste.ee/p/81QeB

**Comment by Electroblob77** [comment] 2020-11-05 13:38
Thanks for reporting. I don't think there's much I can do about this on my end, it appears to be something in the code for Double Slabs.

**Comment by TheidenHD** [comment] 2020-12-05 10:28
I got it working so far, how do i test if it works correctly?

**Comment by Electroblob77** [comment] 2020-12-11 12:46
Install both and run I suppose? Depends what @ALJ323 was doing when the crash happened.

**Comment by TheidenHD** [comment] 2020-12-17 15:42
The crash happend on startup. The problem is that the method in DoubleSlabs Requiems data from Minecraft that is generatet later. I simply implemented a try/catch Block witch return null. My question is if it is problematic when those blocks now interact wit something from Wizardry.

**Comment by Electroblob77** [comment] 2020-12-20 14:49
This should not cause any problems, no. I think it's just part of my model system conflicting with it, but my model system should only care about my models anyway. Assuming this is fixed on DoubleSlabs' end then.

**Closed as completed** 2020-12-20 14:49 UTC
Labels: bug, crash, compatibility, external bug
