### ISSUE TITLE
Ice spells bug

### ISSUE THREAD

**Issue by AkaiRozu** [Electroblob77/Wizardry#573] opened 2020-12-13 02:33 UTC
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.3.1
Environment: Singleplayer

Issue details: while using an spell related to ice with lycanites mobs the mobs glitches and sometimes the full screen itself, the game didn't crash the full bug is in the end of the video.
![2020-12-13 10_28_28-Greenshot](https://user-images.githubusercontent.com/75918712/102001507-15e43780-3d2e-11eb-9c07-810ea2cb0ded.png)
![2020-12-13 10_29_01-Greenshot](https://user-images.githubusercontent.com/75918712/102001510-24caea00-3d2e-11eb-876f-9c71d5226aba.png)

https://drive.google.com/file/d/17224muYcxHogUSg8sCQmptcPelh62Jzd/view?usp=sharing (url)

Other mods involved: [Lycanites mobs]

Link to crash report (if applicable): [Game did not crash]

**Comment by Electroblob77** [comment] 2020-12-13 11:57
Duplicate of #563.

**Closed as completed by Electroblob77** 2020-12-13 11:57 UTC
Labels: bug, duplicate
