### ISSUE TITLE
cant connect to my server

### ISSUE THREAD

**Issue by ZEROX7** [Electroblob77/Wizardry#340] opened 2020-01-15 19:04 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.7
Environment: Server 

tryed updating other mdos and after restart i cant connect even if i undo the changes
join error log
https://pastebin.com/QkevuwLX

**Comment by Electroblob77** [comment] 2020-01-16 18:31
Have you removed any spell packs? You have somehow ended up with spells that are outside the ID range.

**Comment by ZEROX7** [comment] 2020-01-16 21:45
hey there its an issue that pops up if the server crashed before because of the arcane essentials addon, ht ebug that caused the inital crashes is know

**Comment by Electroblob77** [comment] 2020-01-17 12:55
I'm not sure I understand, sorry. Do you mean you've removed arcane essentials because there was a bug with it?

**Comment by ZEROX7** [comment] 2020-01-18 09:31
One specific spell from arcane essentials causes the server to crash when used, and after i started the server again wehn i removed the mod that has the buggy spell in it that error pops up

**Comment by Electroblob77** [comment] 2020-01-20 22:59
On second look something has also gone very wrong with packets, and there's an error from /dank/null going on there, not sure if either of those is anything to do with it.

All I can suggest is to move your existing server world save elsewhere and try it with a fresh one. Let me know if that fixes the problem or not, it'll help me figure out the cause of the issue.

**Comment by ZEROX7** [comment] 2020-01-23 09:04
i got a workaround be temporarily deinstall your mod and all its addons load the save and then i can reinstall your mod, the only thing is that its deletes any progress made in the save itself

**Comment by Electroblob77** [comment] 2020-04-18 16:40
Fixed in 4.2.11.

**Closed as completed by Electroblob77** 2020-04-18 16:40 UTC
Labels: bug
