### ISSUE TITLE
Crash when picking up item entity (from MetalChests); causes secondary crash on re-log

### ISSUE THREAD

**Issue by iamweirdie** [Electroblob77/Wizardry#157] opened 2019-07-26 21:49 UTC
When a player tries to pick up a MetalChest upgrade from the ground, the player gets kicked and will

To Reproduce

Find a dropped MetalChest upgrade
Try to pick it up
Proceed to yell at your computer as you get kicked
Try to login within the radius of the upgrade, keep getting kicked
Versions:

Minecraft: 1.12.2
Forge: 14.23.5.2838
Mod Pack : World of Dragons v. 18.5.215
Mod Name: MetalChests 5.8.9 / Electroblob's Wizardry 4.1.4
Crash Report: https://paste.ubuntu.com/p/vc648MXV4D/

https://github.com/kreezxil/World-of-Dragons/issues/291

**Comment by Electroblob77** [comment] 2019-07-26 22:48
That's the crash on login, which is useful, but doesn't tell me the cause of the original problem. Do you have the crash report from when you first got kicked, by any chance (or could you reproduce it on a different save)?

The crash on login is due to the client receiving wizardry's player data before the client-side player is set up, but this is clearly a secondary issue. It can be patched, but that won't solve the item pickup crash in the first place.

**Comment by kreezxil** [comment] 2019-07-28 14:07
@Electroblob77 I duplicated the effort on my server. this issue was generated on my server to begin with.

the server doesn't crash but it throws one hell of an exception

https://pastebin.com/LArKR7Bi

and all it says to the client, doesn't crash the client either is "Internal Server Error", you can duplicate this by install MetalChests alongside your mod, then throw any of the MetalChests on the ground and try to pick them up.

![image](https://user-images.githubusercontent.com/3880072/62007744-e2901100-b116-11e9-981e-9a4bf662a7b2.png)

Hmm, wondering if that is even true now after seeing the line
```
at snownee.cuisine.events.ForestBatHandler.onItemPickup(ForestBatHandler.java:23) ~[ForestBatHandler.class:?]
```

Your library is clearly on the top of the exception. I will now try with cuisine mod removed from my pack to see if there is a mod conflict happening.

**Comment by kreezxil** [comment] 2019-07-28 14:11
Ok confirmed this a mod conflict issue. I'll now bring the cuisine mod in on this. And I'll be removing cuisine mod from my own pack to resolve the issue. There still might be something you can do with the added information.

**Comment by Electroblob77** [comment] 2019-07-28 15:32
Thanks for investigating. Wizardry isn't even involved in that crash report, which seems to confirm that wizardry's involvement is a secondary issue. I notice the issue you posted on the cuisine repo has been closed because tbone is out of date, could you retry with the latest version? TBone has some recent commits that affect the method in question: https://github.com/T145/tbone/commit/37d899a81bc30123133e1ff364e78721c8fdfa4c

**Comment by kreezxil** [comment] 2019-07-31 14:57
I forgot to mention that removing cuisine mod resolved the issue for me. I had the latest at the time. I don't see the close comment button anymore. hmmm. i think you should close it. If this comes up again ask them if they have cuisine mod installed.

**Comment by kreezxil** [comment] 2019-07-31 14:57
oh i see, my guy opened it. @iamweirdie you can close this issue.

**Closed as completed** 2019-07-31 14:58 UTC
Labels: bug, crash, compatibility, external bug

**Comment by Snownee** [comment] 2019-07-31 15:04
@kreezxil I don't think you should blame the mistake on Cuisine mod. There is no evidence prove that Cuisine causes the crash.

**Comment by Snownee** [comment] 2019-07-31 15:04
@kreezxil I don't think you should blame the mistake on Cuisine mod. There is no evidence prove that is Cuisine cause the crash.
