### ISSUE TITLE
Crashing while casting Flame Ray

### ISSUE THREAD

**Issue by DoctorZoe** [Electroblob77/Wizardry#199] opened 2019-08-21 11:46 UTC
Minecraft version: 1.12.2
Wizardry version: Electroblob's Wizardry - 4.2.1
Environment: Singleplayer/Server

Whenever I cast flame or frost ray, whether through scrolls or wands, it crashes the game.

Other mods involved: [only list mods that are relevant to the problem]
Link to crash report (if applicable): 
- Flame Ray: https://pastebin.com/K5BTxwNX
- Frost Ray: https://pastebin.com/FWSgkju2
[flame ray error.txt](https://github.com/Electroblob77/Wizardry/files/3525132/flame.ray.error.txt)
[frost ray error.txt](https://github.com/Electroblob77/Wizardry/files/3525133/frost.ray.error.txt)

**Comment by KamiSami** [comment] 2019-08-21 19:01
Out of bounds exception: 10, i think i had the same issue too, deleting options files fixed it for me, but no clue if it may come back.. (Again, i am not 100% sure if it still is same issue that i had). I seemed to crash everytime i went to sounds options too. I have currently issue summoning vexes and keep getting out of bounds exception: 5, no clue if it is related to this so i am not gonna post crash report just yet maybe? (Unless Electroblob says it should be posted anyway, then i will)

**Comment by DoctorZoe** [comment] 2019-08-23 23:04
Deleting the configs didn't help at all. :(

**Comment by Electroblob77** [comment] 2019-09-02 12:19
Duplicate of #198.

**Closed as completed by Electroblob77** 2019-09-02 12:19 UTC
Labels: bug, duplicate
