### ISSUE TITLE
syncAdvancements network spam

### ISSUE THREAD

**Issue by LemADEC** [Electroblob77/Wizardry#485] opened 2020-08-02 21:04 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: Server

Issue details:
When a player gets an achievement, the mod is sending multiple time the advancements to this player.
```
[13:16:43] [Server thread/INFO] [ebwizardry]: Synchronising advancements for Nataleenix
[13:16:43] [Server thread/INFO] [ebwizardry]: Synchronising advancements for Nataleenix
[13:16:43] [Server thread/INFO] [ebwizardry]: Synchronising advancements for Nataleenix
[13:16:43] [Server thread/INFO] [ebwizardry]: Synchronising advancements for Nataleenix
[13:16:43] [Server thread/INFO] [ebwizardry]: Synchronising advancements for Nataleenix
[13:16:43] [Server thread/INFO] [ebwizardry]: Synchronising advancements for Nataleenix
[13:16:43] [Server thread/INFO] [ebwizardry]: Synchronising advancements for Nataleenix
[13:16:43] [Server thread/INFO] [ebwizardry]: Synchronising advancements for Nataleenix
[13:16:43] [Server thread/INFO] [ebwizardry]: Synchronising advancements for Nataleenix
[13:16:43] [Server thread/INFO] [ebwizardry]: Synchronising advancements for Nataleenix
[13:16:43] [Server thread/INFO] [ebwizardry]: Synchronising advancements for Nataleenix
[13:16:43] [Server thread/INFO] [minecraft/DedicatedServer]: Nataleenix has made the advancement [Diamonds!]
```
From a quick check of the code, all advancements progress are resent every time this is logged, so there's a network spam going on here.

Other mods involved: https://www.curseforge.com/minecraft/modpacks/fsg-arcania-craft/files/3020551

Link to crash report (if applicable): n/a

**Comment by Electroblob77** [comment] 2020-08-03 21:02
Duplicate of #475.

**Closed as completed by Electroblob77** 2020-08-03 21:02 UTC
Labels: bug, duplicate
