### ISSUE TITLE
Crashing after rebinding next spell key

### ISSUE THREAD

**Issue by Hageshi108** [Electroblob77/Wizardry#91] opened 2018-12-10 20:56 UTC
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.1.2 
Environment: Singleplayer and Multiplayer server. 

Issue details: The next spell key was "B" so I removed all other bindings that was B and I crashed when I pressed B. I cannot join or create new worlds on single player and multiplayer. I have tried restarting, re downloading minecraft jar twitch app folders and completely re downloaded everything. Restarted the server as well.

Other mods involved: Rougelike adventures mod pack

Link to crash report: https://paste.dimdev.org/powezivaco.mccrash

**Comment by Electroblob77** [comment] 2018-12-16 10:32
Duplicate of #90. Please read existing issues in future before posting, your crash report is identical to the one in that issue.

**Closed as completed by Electroblob77** 2018-12-16 10:32 UTC
Labels: duplicate
