### ISSUE TITLE
Electroblob Wizardry is conflicting with the Cyberware and Galacticraft mod.

### ISSUE THREAD

**Issue by MatheusLopes131** [Electroblob77/Wizardry#590] opened 2020-12-28 16:14 UTC
The conflict is directly related to player animations in other mods.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_20.28.2_Forge_1.12.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 12/27/20 4:59 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at electroblob.wizardry.client.animation.PlayerAnimator.onRenderPlayerPostEvent(PlayerAnimator.java:234)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_84_PlayerAnimator_onRenderPlayerPostEvent_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at flaxbeard.cyberware.client.render.RenderPlayerCyberware.func_76986_a(RenderPlayerCyberware.java:149)
	at flaxbeard.cyberware.common.handler.EssentialsMissingHandlerClient.handleMissingSkin(EssentialsMissingHandlerClient.java:123)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_739_EssentialsMissingHandlerClient_handleMissingSkin_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:128)
	at net.minecraft.client.gui.inventory.GuiInventory.func_146976_a(SourceFile:94)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:75)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at electroblob.wizardry.client.animation.PlayerAnimator.onRenderPlayerPostEvent(PlayerAnimator.java:234)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_84_PlayerAnimator_onRenderPlayerPostEvent_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at flaxbeard.cyberware.client.render.RenderPlayerCyberware.func_76986_a(RenderPlayerCyberware.java:149)
	at flaxbeard.cyberware.common.handler.EssentialsMissingHandlerClient.handleMissingSkin(EssentialsMissingHandlerClient.java:123)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_739_EssentialsMissingHandlerClient_handleMissingSkin_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)

-- Entity being rendered --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 199
	Entity Name: zAtaides
	Entity's Exact location: 201.54, 63.00, 811.99
	Entity's Block location: World: (201,63,811), Chunk: (at 9,3,11 in 12,50; contains blocks 192,0,800 to 207,255,815), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderPlayer@5f96ac4b
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:128)
	at net.minecraft.client.gui.inventory.GuiInventory.func_146976_a(SourceFile:94)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:75)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory
	Mouse location: Scaled: (240, 134). Absolute: (960, 540)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['zAtaides'/199, l='MpServer', x=201.54, y=63.00, z=811.99]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (38,64,254), Chunk: (at 6,4,14 in 2,15; contains blocks 32,0,240 to 47,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 769735 game time, 157771 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 115 total; [EntityToucan['Toucan'/512, l='MpServer', x=61.76, y=69.00, z=946.95], EntityPufferFish['Pufferfish'/259, l='MpServer', x=221.75, y=57.00, z=904.87], EntityBat['Morcego'/261, l='MpServer', x=253.64, y=5.14, z=867.34], EntitySkeleton['Esqueleto'/262, l='MpServer', x=246.50, y=5.00, z=864.50], EntityCreeper['Creeper'/263, l='MpServer', x=248.49, y=28.00, z=875.22], EntityReticulatedGiraffe['Reticulated Giraffe'/519, l='MpServer', x=28.40, y=75.00, z=650.35], EntitySkeleton['Esqueleto'/264, l='MpServer', x=250.50, y=39.00, z=877.50], EntityVillager['Aldeão'/266, l='MpServer', x=186.78, y=63.00, z=787.23], EntitySheep['Ovelha'/267, l='MpServer', x=239.81, y=63.00, z=754.16], EntitySheep['Ovelha'/269, l='MpServer', x=270.83, y=63.00, z=736.77], EntityZombie['Zumbi'/273, l='MpServer', x=221.50, y=19.00, z=830.74], EntityBat['Morcego'/275, l='MpServer', x=239.62, y=44.10, z=823.25], EntitySkeleton['Esqueleto'/276, l='MpServer', x=262.50, y=6.00, z=799.50], EntityBrownRat['Brown Rat'/281, l='MpServer', x=275.62, y=70.00, z=938.99], EntityBrownRat['Brown Rat'/282, l='MpServer', x=277.18, y=70.00, z=940.44], EntityCreeper['Creeper'/288, l='MpServer', x=260.84, y=15.00, z=868.41], EntityPufferFish['Pufferfish'/306, l='MpServer', x=278.17, y=62.22, z=789.47], EntityCyberZombie['Cyberzombie'/564, l='MpServer', x=261.50, y=29.00, z=883.50], EntityZombieVillager['Aldeão zumbi'/565, l='MpServer', x=166.50, y=40.00, z=740.50], EntityCreeper['Creeper'/566, l='MpServer', x=246.50, y=30.00, z=877.50], EntityCreeper['Creeper'/570, l='MpServer', x=249.50, y=41.00, z=828.50], EntitySockeyeSalmon['Sockeye Salmon'/318, l='MpServer', x=303.48, y=62.05, z=786.56], EntityZombie['Zumbi'/574, l='MpServer', x=225.50, y=26.00, z=839.50], EntityBrownRat['Brown Rat'/320, l='MpServer', x=297.21, y=71.00, z=708.50], EntityBrownRat['Brown Rat'/321, l='MpServer', x=296.52, y=71.00, z=707.62], EntityZombie['Zumbi'/579, l='MpServer', x=252.50, y=10.00, z=872.19], EntitySockeyeSalmon['Sockeye Salmon'/325, l='MpServer', x=308.93, y=62.08, z=846.44], EntityBrownRat['Brown Rat'/326, l='MpServer', x=324.42, y=68.00, z=753.88], EntityPufferFish['Pufferfish'/327, l='MpServer', x=332.92, y=62.37, z=931.55], EntityPufferFish['Pufferfish'/330, l='MpServer', x=337.90, y=62.14, z=853.73], EntitySockeyeSalmon['Sockeye Salmon'/331, l='MpServer', x=354.32, y=61.29, z=861.94], EntityFrigate['Frigate'/333, l='MpServer', x=369.50, y=71.00, z=756.50], EntityFrigate['Frigate'/334, l='MpServer', x=370.32, y=72.00, z=754.52], EntityHawksbillSeaTurtle['Hawksbill Sea Turtle'/335, l='MpServer', x=368.01, y=71.00, z=761.62], EntityFrigate['Frigate'/336, l='MpServer', x=365.81, y=72.00, z=755.25], EntitySpider['Aranha'/592, l='MpServer', x=252.30, y=5.00, z=756.04], EntityFrigate['Frigate'/337, l='MpServer', x=366.98, y=72.00, z=758.56], EntityItem['item.item.flint'/595, l='MpServer', x=143.59, y=63.00, z=784.97], EntityFish['Blue Fish'/345, l='MpServer', x=339.09, y=63.01, z=906.15], EntityPufferFish['Pufferfish'/346, l='MpServer', x=363.48, y=62.74, z=714.58], EntityZombie['Zumbi'/602, l='MpServer', x=204.50, y=31.00, z=823.50], EntityMorayEel['Moray Eel'/348, l='MpServer', x=368.75, y=60.09, z=951.28], EntityZombie['Zumbi'/605, l='MpServer', x=205.50, y=31.00, z=819.50], EntityZombie['Zumbi'/606, l='MpServer', x=246.50, y=31.00, z=855.50], EntityCreeper['Creeper'/607, l='MpServer', x=272.50, y=42.00, z=888.50], EntityReticulatedGiraffe['Reticulated Giraffe'/355, l='MpServer', x=208.25, y=93.00, z=958.48], EntityBat['Morcego'/616, l='MpServer', x=266.03, y=29.04, z=884.16], EntityBat['Morcego'/618, l='MpServer', x=247.11, y=5.11, z=866.75], EntityCreeper['Creeper'/624, l='MpServer', x=252.50, y=29.00, z=879.50], EntityKoala['Koala'/374, l='MpServer', x=192.71, y=91.00, z=950.48], EntityReticulatedGiraffe['Reticulated Giraffe'/375, l='MpServer', x=208.44, y=95.00, z=968.56], EntityReticulatedGiraffe['Reticulated Giraffe'/376, l='MpServer', x=192.34, y=91.00, z=948.47], EntityReticulatedGiraffe['Reticulated Giraffe'/377, l='MpServer', x=201.44, y=94.00, z=966.42], EntityCreeper['Creeper'/634, l='MpServer', x=250.50, y=64.00, z=787.50], EntitySkeleton['Esqueleto'/635, l='MpServer', x=242.50, y=41.00, z=834.50], EntitySpider['Aranha'/641, l='MpServer', x=247.97, y=32.00, z=820.01], EntityZombie['Zumbi'/643, l='MpServer', x=128.50, y=16.00, z=800.50], EntitySkeleton['Esqueleto'/644, l='MpServer', x=263.50, y=32.00, z=860.50], EntitySkeleton['Esqueleto'/649, l='MpServer', x=253.50, y=5.00, z=828.50], EntityReticulatedGiraffe['Reticulated Giraffe'/394, l='MpServer', x=186.75, y=92.00, z=945.72], EntitySpider['Aranha'/650, l='MpServer', x=151.50, y=63.00, z=855.50], EntityEnderman['Enderman'/654, l='MpServer', x=245.50, y=5.00, z=763.50], EntityReticulatedGiraffe['Reticulated Giraffe'/399, l='MpServer', x=200.55, y=91.00, z=969.95], EntityReticulatedGiraffe['Reticulated Giraffe'/400, l='MpServer', x=203.59, y=94.00, z=965.28], EntityBat['Morcego'/660, l='MpServer', x=241.65, y=41.58, z=827.63], EntityBat['Morcego'/661, l='MpServer', x=239.89, y=41.24, z=841.23], EntityKoala['Koala'/407, l='MpServer', x=184.59, y=98.00, z=974.40], EntitySkeleton['Esqueleto'/663, l='MpServer', x=163.49, y=53.00, z=865.30], EntityReticulatedGiraffe['Reticulated Giraffe'/408, l='MpServer', x=160.46, y=85.00, z=954.57], EntityKoala['Koala'/409, l='MpServer', x=166.61, y=90.00, z=971.69], EntityKoala['Koala'/410, l='MpServer', x=185.63, y=92.00, z=977.79], EntityPlayerSP['zAtaides'/199, l='MpServer', x=201.54, y=63.00, z=811.99], EntityLatchedRenderer['desconhecida'/413, l='MpServer', x=8.50, y=65.00, z=8.50], EntityZombie['Zumbi'/678, l='MpServer', x=262.50, y=36.00, z=880.50], EntitySkeleton['Esqueleto'/679, l='MpServer', x=139.50, y=64.00, z=889.50], EntityZombie['Zumbi'/681, l='MpServer', x=142.50, y=64.00, z=884.50], EntityZombie['Zumbi'/682, l='MpServer', x=125.50, y=20.00, z=818.50], EntityFish['Blue Fish'/427, l='MpServer', x=121.93, y=61.73, z=971.18], EntityCyberZombie['Cyberzombie'/683, l='MpServer', x=265.50, y=26.00, z=850.50], EntityFish['Blue Fish'/428, l='MpServer', x=117.93, y=63.02, z=961.50], EntityTropicalFish['entity.zawa.marinetang.name'/429, l='MpServer', x=110.54, y=62.31, z=949.75], EntitySpider['Aranha'/685, l='MpServer', x=256.50, y=63.00, z=748.50], EntityZombie['Zumbi'/687, l='MpServer', x=248.50, y=40.00, z=821.50], EntityCreeper['Creeper'/688, l='MpServer', x=251.50, y=40.00, z=824.50], EntitySkeleton['Esqueleto'/694, l='MpServer', x=170.36, y=64.00, z=798.14], EntityCreeper['Creeper'/695, l='MpServer', x=250.50, y=40.00, z=822.50], EntityZombie['Zumbi'/696, l='MpServer', x=246.50, y=40.00, z=822.50], EntityBat['Morcego'/706, l='MpServer', x=187.47, y=33.06, z=809.38], EntityBat['Morcego'/708, l='MpServer', x=128.99, y=15.10, z=817.51], EntityCreeper['Creeper'/711, l='MpServer', x=254.50, y=4.00, z=751.50], EntityPufferFish['Pufferfish'/200, l='MpServer', x=105.71, y=62.74, z=826.05], EntityFish['Blue Fish'/201, l='MpServer', x=108.78, y=62.19, z=821.53], EntityChickensChicken['Flint Chicken'/202, l='MpServer', x=142.40, y=63.74, z=784.95], EntitySockeyeSalmon['Sockeye Salmon'/204, l='MpServer', x=87.64, y=63.12, z=859.22], EntitySkeleton['Esqueleto'/716, l='MpServer', x=169.50, y=64.00, z=877.50], EntitySpider['Aranha'/719, l='MpServer', x=244.50, y=63.00, z=754.50], EntityBrownRat['Brown Rat'/211, l='MpServer', x=156.25, y=64.00, z=737.47], EntityPufferFish['Pufferfish'/212, l='MpServer', x=122.15, y=63.00, z=797.15], EntityFish['Blue Fish'/213, l='MpServer', x=127.37, y=61.96, z=799.85], EntityBlackRhinoceros['Black Rhinoceros'/216, l='MpServer', x=163.93, y=71.00, z=927.92], EntityBrownRat['Brown Rat'/218, l='MpServer', x=153.95, y=68.00, z=695.89], EntitySkeleton['Esqueleto'/220, l='MpServer', x=141.49, y=53.00, z=866.75], EntityZombie['Zumbi'/227, l='MpServer', x=166.03, y=53.00, z=861.30], EntitySkeleton['Esqueleto'/229, l='MpServer', x=156.50, y=14.00, z=884.50], EntityCreeper['Creeper'/230, l='MpServer', x=148.50, y=52.00, z=880.79], EntityBat['Morcego'/231, l='MpServer', x=162.25, y=55.10, z=865.25], EntityZombie['Zumbi'/232, l='MpServer', x=157.80, y=53.00, z=860.51], EntityBat['Morcego'/235, l='MpServer', x=177.54, y=18.67, z=763.25], EntityBrownRat['Brown Rat'/237, l='MpServer', x=176.27, y=64.00, z=754.44], EntityBlackRhinoceros['Black Rhinoceros'/493, l='MpServer', x=56.34, y=70.00, z=916.81], EntityBrownRat['Brown Rat'/241, l='MpServer', x=232.57, y=66.00, z=900.29], EntityReticulatedGiraffe['Reticulated Giraffe'/242, l='MpServer', x=213.44, y=80.00, z=933.89], EntityReticulatedGiraffe['Reticulated Giraffe'/243, l='MpServer', x=215.89, y=80.00, z=939.38], EntityBrownRat['Brown Rat'/250, l='MpServer', x=236.55, y=69.00, z=677.09], EntityBat['Morcego'/251, l='MpServer', x=225.75, y=21.10, z=837.42]]
	Retry entities: 1 total; [EntityLatchedRenderer['desconhecida'/413, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1452607968 bytes (1385 MB) / 3087007744 bytes (2944 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version           | Source                                  | Signature                                |
	|:------ |:------------------ |:----------------- |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft          | 1.12.2            | minecraft.jar                           | None                                     |
	| LCHIJA | mcp                | 9.42              | minecraft.jar                           | None                                     |
	| LCHIJA | FML                | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar           | None                                     |
	| LCHIJA | forge              | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar           | None                                     |
	| LCHIJA | xaerominimap_core  | 1.12.2-1.0        | minecraft.jar                           | None                                     |
	| LCHIJA | aether_legacy      | 1.5.2             | aether-1.12.2-v1.5.2.jar                | None                                     |
	| LCHIJA | baubles            | 1.5.2             | Baubles-1.12-1.5.2.jar                  | None                                     |
	| LCHIJA | bookshelf          | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bookworm           | 1.12.2-2.5.2.1    | bookworm-1.12.2-2.5.2.1.jar             | None                                     |
	| LCHIJA | chickens           | 6.0.4             | chickens-6.0.4.jar                      | None                                     |
	| LCHIJA | ctm                | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar               | None                                     |
	| LCHIJA | jei                | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar               | None                                     |
	| LCHIJA | chisel             | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar            | None                                     |
	| LCHIJA | cxlibrary          | 1.6.1             | cxlibrary-1.12.1-1.6.1.jar              | None                                     |
	| LCHIJA | cyberware          | 0.2.11.26         | cyberware-1.12.2-0.2.11.26.jar          | None                                     |
	| LCHIJA | ebwizardry         | 4.3.1             | ElectroblobsWizardry-4.3.1-MC1.12.2.jar | None                                     |
	| LCHIJA | eplus              | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | extrautils2        | 1.0               | extrautils2-1.12-1.9.9.jar              | None                                     |
	| LCHIJA | cfm                | 6.3.1             | furniture-6.3.1-1.12.2.jar              | None                                     |
	| LCHIJA | hatchery           | 2.2.2             | hatchery-1.12.2-2.2.2.jar               | None                                     |
	| LCHIJA | waila              | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar             | None                                     |
	| LCHIJA | ichunutil          | 7.2.1             | iChunUtil-1.12.2-7.2.1.jar              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | inventorypets      | 2.0.6             | inventorypets-1.12-2.0.6.jar            | None                                     |
	| LCHIJA | ironchest          | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar         | None                                     |
	| LCHIJA | mekanism           | 1.12.2-9.8.3.390  | Mekanism-1.12.2-9.8.3.390.jar           | None                                     |
	| LCHIJA | mekanismgenerators | 1.12.2-9.8.3.390  | MekanismGenerators-1.12.2-9.8.3.390.jar | None                                     |
	| LCHIJA | mjrlegendslib      | 1.12.2-1.2.0      | MJRLegendsLib-1.12.2-1.2.0.jar          | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | morechickens       | 3.1.0             | morechickens-1.12.2-3.1.0.jar           | None                                     |
	| LCHIJA | morefurnaces       | 1.10.5            | MoreFurnaces-1.12.2-1.10.6.jar          | None                                     |
	| LCHIJA | mutantbeasts       | 1.12.2-1.0.1      | MutantBeasts-1.12.2-1.0.1.jar           | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
	| LCHIJA | naturescompass     | 1.8.5             | NaturesCompass-1.12.2-1.8.5.jar         | None                                     |
	| LCHIJA | portalgun          | 7.1.0             | PortalGun-1.12.2-7.1.0.jar              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | projecte           | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar             | None                                     |
	| LCHIJA | roost              | 2.0.10            | roost-1.12.2-2.0.10.jar                 | None                                     |
	| LCHIJA | xaerominimap       | 20.28.2           | Xaeros_Minimap_20.28.2_Forge_1.12.jar   | None                                     |
	| LCHIJA | zawa               | 1.12.2-2.1.0      | zawa-1.12.2-2.1.0.jar                   | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LCHIJA | llibrary           | 1.7.20            | llibrary-1.7.20-1.12.2.jar              | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | jurassicraft       | 2.1.23            | JurassiCraft-1.12.2-2.1.23.jar          | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
XaeroMinimapPlugin (Xaeros_Minimap_20.28.2_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14757 Compatibility Profile Context 20.12.1 27.20.14501.28009' Renderer: 'Radeon(TM) RX 460 Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Radeon(TM) RX 460 Graphics GL version 4.6.14757 Compatibility Profile Context 20.12.1 27.20.14501.28009, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Português (Brasil)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz

**Comment by MatheusLopes131** [comment] 2020-12-28 16:15
![Mods](https://user-images.githubusercontent.com/68877889/103228077-b6ca1980-490e-11eb-9e52-0d0fce168732.JPG)
 
Mods image

**Comment by Shibva** [comment] 2020-12-28 22:05
this issue does nto exist, I have the overlay renders for the cyberware parts disabled, this is an issue with trinket renderig

try to disable the cyberware redner option to see if that fixes it, if so, then thats the issue

**Comment by Electroblob77** [comment] 2020-12-29 12:49
Duplicate of #551.

**Closed as completed by Electroblob77** 2020-12-29 12:49 UTC
Labels: bug, duplicate
