### ISSUE TITLE
Spectral Sword does not disappear in offhand

### ISSUE THREAD

**Issue by valdotexe** [Electroblob77/Wizardry#523] opened 2020-10-24 23:46 UTC
When a Spectral Sword, *or any spectral item since they most likely share the same dissapearence code*, way is held in the offhand and runs out of durability, the sword remains in your offhand and the durability starts going to negative values. Putting the item back into the inventory deletes the item properly

**Comment by Electroblob77** [comment] 2020-10-25 11:28
Duplicate of #493.

**Closed as completed by Electroblob77** 2020-10-25 11:28 UTC
Labels: bug, duplicate
