### ISSUE TITLE
it may be related to the sound issues

### ISSUE THREAD

**Issue by ValentineBlaze** [Electroblob77/Wizardry#211] opened 2019-08-23 04:09 UTC
this may be a dupe and sorry if it is

Minecraft version: 1.12.2  
Wizardry version: 4.2.1
Environment: Server 

Issue details: my friend entered a wizard tower looked at the wizard and keeps on crashing now whenever they try to rejoin

Other mods involved: probably some conflictions in the sound library with midnight and dynamic surroundings plus probably another mod that is the real issue that I have no clue

Link to crash report (if applicable):https://paste.dimdev.org/sijeyuwaso.mccrash

**Comment by caligator** [comment] 2019-08-24 05:23
one of the people on my server is having the same issue in the overworld on the public server for my pack- reproduced with midnight in the packs mods. I've personally had crashes around the same places-- in specific it seems that the evil wizards spawned around runestones cause the crash. 
[crash-2019-08-23_23.52.13-client.txt](https://github.com/Electroblob77/Wizardry/files/3536894/crash-2019-08-23_23.52.13-client.txt)

**Comment by Electroblob77** [comment] 2019-09-02 14:12
Yes, this is a duplicate of #198.

**Closed as completed by Electroblob77** 2019-09-02 14:12 UTC
Labels: bug, duplicate
