### ISSUE TITLE
Soulbind Remains after death

### ISSUE THREAD

**Issue by DoctorMage** [Electroblob77/Wizardry#743] opened 2021-12-15 20:12 UTC
Minecraft version: 1.12.2 
Wizardry version: 4.3.4 
Environment: Server

Issue details:When casted on a player soulbind remains effective unless the caster dies aka the player that soulbind is cast on will take the redirect damage 
Other mods involved: Modpack is rad 1.48 - https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]
Client Logs
[latest(2).log](https://github.com/Electroblob77/Wizardry/files/7722409/latest.2.log)
Server Logs
[2021-12-15-3.log](https://github.com/Electroblob77/Wizardry/files/7722411/2021-12-15-3.log)
Video
https://streamable.com/eujecn

**Comment by WinDanesz** [comment] 2021-12-27 11:41
Duplicate of #619

**Comment by WinDanesz** [comment] 2022-02-03 10:59
Fixed in f9681d4c662f630fb17fea2c4cb5869ea6fffb3c

**Closed as completed by WinDanesz** 2022-02-03 10:59 UTC
Labels: bug, duplicate
