### ISSUE TITLE
ArrayIndexOutOfBoundsException in wand NBT data

### ISSUE THREAD

**Issue by Silivek** [Electroblob77/Wizardry#90] opened 2018-12-07 00:26 UTC
Shift-right-clicked with novice wand, game crashed and won't let me in a world anymore.
https://paste.dimdev.org/nonuviqowe.mccrash
Minecraft version 1.12.2
Wizardry version 4.1.2
Singleplayer
Roguelike, Adventures, and Dungeons modpack

**Comment by Electroblob77** [comment] 2018-12-09 22:08
I've definitely seen a crash report like that before, it's to do with the way NBT data is initialised. I have added a fix for this in my dev branch so this will be fixed for the next update.

I'm not sure what shift-right-clicking has to do with this, it's a rendering crash caused by the text that appears above the hotbar when you switch items. Presumably it's not letting you into the world because that's appearing every time you log in. Unfortunately there's not a lot that can be done about that until the issue is fixed.

**Comment by Silivek** [comment] 2018-12-09 22:26
I figured out something past it. I had changed the next spell key and I believe I might've pressed the new key before the crash. I was looking around and I just left the next and previous spell keys at their default, and it works perfectly. Thanks anyway, and merry Christmas! (P.S. I would love to know if you fix the keybind problem, I don't like using N and B)

**Comment by Electroblob77** [comment] 2018-12-16 10:30
What did you rebind it to? There have been issues in the past related to using non-standard keybinds (either mouse buttons or keys with modifiers like ctrl).

**Comment by Silivek** [comment] 2018-12-16 15:02
I bound the previous spell key to comma and next spell to period

**Comment by Electroblob77** [comment] 2018-12-25 18:27
I've marked this issue as high priority because it's coming up a lot and stopping people using /give with wands. I'm planning on releasing a hotfix for this and a few other simple fixes as soon as I get the chance.

In the meantime, in some cases you may be able to avoid this issue by placing new wands in an arcane workbench and pressing apply (there need not be any books or crystals) before using it.

**Closed as completed** 2019-01-04 22:01 UTC
Labels: high priority, crash
