### ISSUE TITLE
Caught exception caused by java.lang.NullPointerException

### ISSUE THREAD

**Issue by imCruxi** [Electroblob77/Wizardry#768] opened 2022-02-05 01:58 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  CreativePatchingLoader (CreativeCore_v1.10.69_mc1.12.2.jar)
  OTGCorePlugin (OTG-Core.jar)
  ShoulderPlugin (ShoulderSurfing-1.12.2-2.2.1.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 2/4/22 10:41 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Electroblob's Wizardry (ebwizardry)
Caused by: java.lang.NullPointerException
	at electroblob.wizardry.client.gui.handbook.GuiWizardHandbook.getHandbookResource(GuiWizardHandbook.java:466)
	at electroblob.wizardry.client.gui.handbook.GuiWizardHandbook.loadHandbookFile(GuiWizardHandbook.java:409)
	at electroblob.wizardry.client.ClientProxy$$Lambda$192/1048281966.func_110549_a(Unknown Source)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at electroblob.wizardry.client.ClientProxy.registerResourceReloadListeners(ClientProxy.java:167)
	at electroblob.wizardry.Wizardry.preInit(Wizardry.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 185219208 bytes (176 MB) / 1256718336 bytes (1198 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                | Source                                                | Signature                                |
	|:----- |:-------------------- |:---------------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2                 | minecraft.jar                                         | None                                     |
	| LCH   | mcp                  | 9.42                   | minecraft.jar                                         | None                                     |
	| LCH   | FML                  | 8.0.99.99              | forge-1.12.2-14.23.5.2859.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2859           | forge-1.12.2-14.23.5.2859.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy    | 1.0.0                  | minecraft.jar                                         | None                                     |
	| LCH   | otgcore              | 1.12.2-v9.4            | minecraft.jar                                         | None                                     |
	| LCH   | securitycraft        | v1.8.14                | 1.12.2SecurityCraftv1.8.14.jar                        | None                                     |
	| LCH   | creativecore         | 1.10.0                 | CreativeCore_v1.10.69_mc1.12.2.jar                    | None                                     |
	| LCH   | ambientsounds        | 3.0                    | AmbientSounds_v3.0.18_mc1.12.2.jar                    | None                                     |
	| LCH   | antiqueatlas         | 4.6.3                  | antiqueatlas-1.12.2-4.6.3.jar                         | None                                     |
	| LCH   | antiqueatlasoverlay  | 1.2                    | antiqueatlas-1.12.2-4.6.3.jar                         | None                                     |
	| LCH   | astikorcarts         | 1.12.2-0.1.2.8         | astikorcarts-1.12.2-0.1.2.8.jar                       | None                                     |
	| LCH   | openterraingenerator | v9.4                   | OpenTerrainGenerator-1.12.2-v9.4.jar                  | None                                     |
	| LCH   | biomebundle          | 5.1                    | Biome_Bundle-1.12.2-v6.1.jar                          | None                                     |
	| LCH   | chunkpregenerator    | 2.5.0                  | Chunk+Pregenerator-V1.12-2.5.1.jar                    | None                                     |
	| LCH   | dawnoftimebuilder    | 1.0.7                  | dawnoftime_builder_edition-1.0.7.jar                  | None                                     |
	| LCH   | dragonmounts         | 1.12.2-1.6.3           | DragonMounts2-1.12.2-1.6.3.jar                        | None                                     |
	| LCH   | dungeontactics       | DT-0.16.9              | DungeonTactics-1.12.2-0.16.9.jar                      | None                                     |
	| LCH   | orelib               | 3.6.0.1                | OreLib-1.12.2-3.6.0.1.jar                             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround            | 3.6.1.0                | DynamicSurroundings-1.12.2-3.6.1.0.jar                | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | jei                  | 4.15.0.289             | jei_1.12.2-4.15.0.289.jar                             | None                                     |
	| LCE   | ebwizardry           | 4.3.4                  | ElectroblobsWizardry-4.3.4-MC1.12.2.jar               | None                                     |
	| LC    | enhancedvisuals      | 1.3.0                  | EnhancedVisuals_v1.4.4_mc1.12.2.jar                   | None                                     |
	| LC    | exoticbirds          | 1.0                    | Exotic+Birds+1.12.2-3.2.0.jar                         | None                                     |
	| LC    | eyesinthedarkness    | 0.1.0                  | EyesInTheDarkness-0.1.0.jar                           | None                                     |
	| LC    | waila                | 1.8.26                 | Hwyla-1.8.26-B41_1.12.2.jar                           | None                                     |
	| LC    | ignitehud            | 1.12-b0.1.1            | ignitehud_1.12-b0.1.1.jar                             | None                                     |
	| LC    | jjskill              | 1.0.35                 | JJ+Skill+1.12-1.12.2-v1.0.35.jar                      | None                                     |
	| LC    | mantle               | 1.12-1.3.3.55          | Mantle-1.12-1.3.3.55.jar                              | None                                     |
	| LC    | medieval_craft       | 1.14.4                 | MedievalCraft-1.12.2-1.16.0.jar                       | None                                     |
	| LC    | millenaire           | Millénaire 8.1.1       | millenaire-1.12.2-8.1.1.jar                           | None                                     |
	| LC    | mobends              | 1.0.0-beta-20.06.20    | MoBends_1.12.2-1.0.0-beta-20.06.20.jar                | None                                     |
	| LC    | llibrary             | 1.7.20                 | llibrary-1.7.20-1.12.2.jar                            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | mowziesmobs          | 1.5.8                  | mowziesmobs-1.5.8.jar                                 | None                                     |
	| LC    | mysticalworld        | 1.12.2-1.10.0          | mysticalworld-1.12.2-1.10.0.jar                       | None                                     |
	| LC    | netherportalfix      | 5.3.17                 | NetherPortalFix_1.12.1-5.3.17.jar                     | None                                     |
	| LC    | recipehandler        | 0.13                   | NoMoreRecipeConflict-0.13(1.12.2).jar                 | None                                     |
	| LC    | patchouli            | 1.0-23.6               | Patchouli-1.0-23.6.jar                                | None                                     |
	| LC    | playerrevive         | 1.0                    | PlayerRevive_v1.2.40_mc1.12.2.jar                     | None                                     |
	| LC    | rustic               | 1.1.7                  | rustic-1.1.7.jar                                      | None                                     |
	| LC    | shouldersurfing      | 2.2.1                  | ShoulderSurfing-1.12.2-2.2.1.jar                      | d6261bb645f41db84c74f98e512c2bb43f188af2 |
	| LC    | snowaccumulation     | 1.0.0                  | SnowAccumulation-Mod-1.12.2.jar                       | None                                     |
	| LC    | tconstruct           | 1.12.2-2.13.0.183      | TConstruct-1.12.2-2.13.0.183.jar                      | None                                     |
	| LC    | tcomplement          | 1.12.2-0.4.3           | TinkersComplement-1.12.2-0.4.3.jar                    | None                                     |
	| LC    | tombstone            | 4.4.7                  | tombstone-1.12.2-4.4.7.jar                            | None                                     |
	| LC    | gvc                  | 1.2.5                  | VoiceChatReloaded-1.2.5.jar                           | None                                     |
	| LC    | drplibrary           | 1.12.2-0.1.3-SNAPSHOT  | drplibrary-1.12.2-0.1.3-SNAPSHOT-20190129.054240.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LC    | drpcmblueprints      | 1.12.2-1.2.3           | drpcmblueprints-1.12.2-1.2.3.jar                      | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LC    | drpcmmaarg           | 1.12.2-0.10.0-SNAPSHOT | drpcmmaarg-1.12.2-0.10.0-SNAPSHOT-20181116.094036.jar | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LC    | drpcmguis            | 1.12.2-0.0.2-SNAPSHOT  | drpcmguis-1.12.2-0.0.1-SNAPSHOT-20181125.020253.jar   | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LC    | drpcore              | 1.12.2-0.4.7           | drpcore-1.12.2-0.4.8.jar                              | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LC    | drpcmlocks           | 1.12.2-1.0.1           | drpcmlocks-1.12.2-1.0.0-SNAPSHOT-20181126.011203.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LC    | drpmedieval          | 1.12.2-0.3.6           | drpmedieval(projectBrazier)-1.12.2-0.3.6.jar          | None                                     |
	| LC    | mysticallib          | 1.12.2-1.11.0          | mysticallib-1.12.2-1.11.0.jar                         | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
CreativePatchingLoader (CreativeCore_v1.10.69_mc1.12.2.jar)
  
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
ShoulderPlugin (ShoulderSurfing-1.12.2-2.2.1.jar)
  com.teamderpy.shouldersurfing.asm.transformers.EntityPlayerRayTrace
  com.teamderpy.shouldersurfing.asm.transformers.EntityRendererGetMouseOver
  com.teamderpy.shouldersurfing.asm.transformers.EntityRendererGetMouseOver2
  com.teamderpy.shouldersurfing.asm.transformers.EntityRendererOrientCamera
  com.teamderpy.shouldersurfing.asm.transformers.EntityRendererRayTrace
  com.teamderpy.shouldersurfing.asm.transformers.GuiIngameRenderAttackIndicator
  com.teamderpy.shouldersurfing.asm.transformers.GuiCrosshairsBCRenderAttackIndicator
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.5174' Renderer: 'Intel(R) HD Graphics 530'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 21.20.16.5174
	OpenGlRenderer: Intel(R) HD Graphics 530
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by WinDanesz** [comment] 2022-02-05 10:26
1) What is your Minecraft client language?
2) What is your OS language?

**Comment by WinDanesz** [comment] 2022-02-05 10:27
Potentially a duplicate of #764

**Comment by imCruxi** [comment] 2022-02-05 13:41
> 

MC Client language: Spanish (Argentina)
OS language: Spanish (Argentina
![language](https://user-images.githubusercontent.com/99058402/152644653-52d789a5-87f3-476e-b226-2a14460e0e18.png)
)

**Comment by WinDanesz** [comment] 2022-02-05 16:04
Then please try setting your MC language to english to see if the crash still happens. You might need to temporarily remove the mod if you can't load up the game with Wizardry.

**Comment by WinDanesz** [comment] 2022-02-05 16:08
If the above doesn't help, you are using Forge 14.23.5.2859, try to downgrade to e g. 2854 to see if it solves the issue. I'll investigate it later anyways.

**Comment by imCruxi** [comment] 2022-02-05 19:07
Placing the language in English didn't solve it. But using forge 2854 apparently does. (When the problem appears again I will comment)

**Comment by WinDanesz** [comment] 2022-02-05 21:40
In that case this is definitely resembling #764

**Comment by imCruxi** [comment] 2022-02-05 23:49
the problem continues 😢

**Comment by WinDanesz** [comment] 2022-02-06 00:19
Even with Forge 2854? You previously said that didn't crash?

**Comment by imCruxi** [comment] 2022-02-06 00:27
Yes that's how it is. It worked for a while, I changed the language to Spanish and it was still working. But now it crash

it seems that the problem is the language

**Comment by WinDanesz** [comment] 2022-02-06 06:35
What do you mean by "it was still working" and now it crashes.. What changed?
What are the steps to replicate the issue?

**Comment by imCruxi** [comment] 2022-02-06 06:45
The game worked fine with the English language, then I change it to Spanish and it continues to work fine until you close it and reopen it

**Comment by WinDanesz** [comment] 2022-02-07 22:02
Sadly I couldn't replicate this issue with forge 14.23.5.2860 and spanish settings.
From where did you download Wizardry? CurseForge?
Have you tried 14.23.5.2860?

**Closed as completed** 2022-07-08 17:42 UTC
Labels: bug

**Comment by WinDanesz** [comment] 2022-09-30 10:14
The loadHandbook config can mitigate this issue
