### ISSUE TITLE
Crash when constructing

### ISSUE THREAD

**Issue by blind1013** [Electroblob77/Wizardry#585] opened 2020-12-21 15:38 UTC
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.1 [change as necessary]
Environment: Singleplayer

Issue details: start up minecraft with only electroblob mod and it crashed

Other mods involved: -

Link to crash report (if applicable):
[crash-2020-12-21_23.33.00-client.txt](https://github.com/Electroblob77/Wizardry/files/5725130/crash-2020-12-21_23.33.00-client.txt)

**Comment by Electroblob77** [comment] 2020-12-21 16:32
Duplicate of #552.

**Closed as completed by Electroblob77** 2020-12-21 16:32 UTC
Labels: bug, duplicate
