### ISSUE TITLE
Server crash on necromancy spell cast

### ISSUE THREAD

**Issue by xskipy** [Electroblob77/Wizardry#509] opened 2020-10-08 16:53 UTC
Minecraft version: 1.12.2 
Wizardry version: 4.2.11
Environment: LAN game/Server 

Issue details: When the wizards spawn from the pink block the game crashes. From the log it seems it crashes when some effect on hit tries to be executed.

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report : https://pastebin.com/g7R4BRcK

**Comment by Electroblob77** [comment] 2020-10-10 12:16
Duplicate of #500. This is a bug in arcane essentials, please update to the latest _beta_ version of arcane essentials to fix it.

**Closed as completed by Electroblob77** 2020-10-10 12:16 UTC
Labels: bug, duplicate
