### ISSUE TITLE
IndexOutOfBoundsException in spell glyph data packet

### ISSUE THREAD

**Issue by sheil1488** [Electroblob77/Wizardry#384] opened 2020-03-23 14:02 UTC
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.1.4 [change as necessary]
Environment: Singleplayer

Issue details: Loading a world after updating the mod

Other mods involved: It's a modpack IDK which one can cause a problem, the list of mods is available at the link below:

Link to crash report (if applicable): https://paste.dimdev.org/vufovaxugi.mccrash

Thanks!

**Comment by Tora-B** [comment] 2020-03-24 00:37
Probably a duplicate of #253. Try updating Arcane Essentials to the latest beta version.

**Comment by sheil1488** [comment] 2020-03-24 15:42
I don't have Arcane Essentials bro

**Comment by Electroblob77** [comment] 2020-03-31 17:54
@Tora-B At first glance it does look like it, but this is actually a separate issue.

@Tauma-png Which modpack are you using, which version of that modpack were you running before and which version are you running now?

**Comment by Electroblob77** [comment] 2020-03-31 20:14
May also be the same as #340. I think I'll add a safety check with a printout to the console so that this doesn't cause a crash, I don't know why it would happen (other than by removing spell packs) but it's client-side so it's unlikely to break anything that badly anyway.

**Comment by sheil1488** [comment] 2020-04-02 13:29
Hey, thanks for answering, I'm using Roguelike Adventure and Dungeons modpack, I was running on the 1.36 and now on 1.37, I just created a new world and it works, seems that I cannot load a previous version world only

**Closed as completed** 2020-04-13 21:03 UTC
Labels: bug, crash

**Comment by Electroblob77** [comment] 2020-04-13 21:29
That makes sense. I've added a check so it won't crash the game any more, you may notice some weirdness when updating old worlds but it shouldn't affect the save.
