### ISSUE TITLE
I get a crash report whenever I use a spell

### ISSUE THREAD

**Issue by Wiral2** [Electroblob77/Wizardry#232] opened 2019-09-02 20:35 UTC
Minecraft version: 1.12.2 
Wizardry version: 4.1.4 
Environment: Singleplayer/LAN game

Issue details: I recently updated the mod and now whenever I use any spell I get this crash report: https://paste.dimdev.org/izotixoyug.mccrash
I have vanilla fix, so the game itself doesn't crash. But I get bombarded with messages "unknown error has occured"

**Comment by Wiral2** [comment] 2019-09-02 20:40
Also whenever I hit mobs from lycanitesmobs with the Ice axe, they get extremely weird textures.

**Comment by Electroblob77** [comment] 2019-09-03 13:00
Probably a duplicate of #198. The second thing may be related to #170, Lycanite's mobs often behaves weirdly anyway.

**Closed as completed by Electroblob77** 2019-09-03 13:00 UTC
Labels: bug, duplicate

**Comment by Wiral2** [comment] 2019-09-06 05:22
Was the problem fixed in the newest update?
