### ISSUE TITLE
Minecraft Failed To Start !

### ISSUE THREAD

**Issue by ThicUncleSam** [Electroblob77/Wizardry#344] opened 2020-01-25 04:56 UTC
Minecraft version: 1.12.2 
Wizardry version: 4.2.7
Environment: LAN game

Issue details: My brother and I put a little modpack together just for the two of us to play and upon installing everything together as we went, he launched up his Minecraft and it ran fine, I launched up mine and I am getting a Minecraft failed to start screen.

Other mods involved: I'm pretty sure no other mods are messing with it as my brother who has the same mods installed can play and I can not.

Link to crash report (if applicable): https://paste.dimdev.org/epimaqufiz.mccrash

**Comment by Tora-B** [comment] 2020-01-25 08:02
What launcher are you using? Do you have your modpack in a separate instance or folder from the default vanilla location? Can you post your options.txt file?

**Comment by Electroblob77** [comment] 2020-01-25 17:07
Duplicate of #342.

**Closed as completed by Electroblob77** 2020-01-25 17:07 UTC
Labels: duplicate
