### ISSUE TITLE
Cooldown upgrade+warlock armor=bricked wand slot

### ISSUE THREAD

**Issue by varappdev** [Electroblob77/Wizardry#613] opened 2021-01-29 13:44 UTC
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.3.3 
Environment: Singleplayer

Issue details: Applying the cooldown upgrade to any wand and using full warlock set will cause the spell slot to be bricked, it will never recharge again even if you swap the spell.

**Comment by Electroblob77** [comment] 2021-01-30 17:37
Duplicate of #603.

**Closed as completed by Electroblob77** 2021-01-30 17:37 UTC
Labels: bug, duplicate
