### ISSUE TITLE
Forcefield Spell Bug? or how add friend in forsefield? 

### ISSUE THREAD

**Issue by zifzirf** [Electroblob77/Wizardry#506] opened 2020-10-01 05:45 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.11

Question details: The problem is that when a friend is added to the friend list, he cannot enter the force field to be protected. 
If this is the norm, then just write me this) but of course, I would like a friend to be in my protection, otherwise the meaning of playing with friends disappears
Other mods involved: -

P.s. im Russian boy and i bad writing in English, sorry for that...

**Comment by Tora-B** [comment] 2020-10-01 11:29
Duplicate of #320. Allies _should_ be able to pass through the forcefield, and it's not clear why it doesn't work.

**Comment by zifzirf** [comment] 2020-10-02 08:41
Thanks i dont see issue

**Comment by Electroblob77** [comment] 2020-10-02 12:56
Yep. Any information on this would be appreciated, particularly whether it's broken in all cases, or just sometimes. I will do some testing myself as well to try and get to the bottom of it.

**Closed as completed by Electroblob77** 2020-10-02 12:56 UTC
Labels: duplicate, question
