### ISSUE TITLE
Electroblob Crashes on startup

### ISSUE THREAD

**Issue by MagnusOneil** [Electroblob77/Wizardry#521] opened 2020-10-24 12:55 UTC
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3 [change as necessary]
Environment: So far Single Player. Plan to make it LAN later to play with friends

Issue details: So I was loading up the mod, y'know , going through the whole hammer loading screen and all, then where I get to the point to where I can make a world. It just says there was a crash and that EBwizardy was the issue.

Other mods involved: I have no idea. I don't think any are

Link to crash report: https://pastebin.com/Gy7GZKZr

**Comment by Electroblob77** [comment] 2020-10-24 22:08
Duplicate of #517.

**Closed as completed by Electroblob77** 2020-10-24 22:08 UTC
Labels: bug, duplicate
