### ISSUE TITLE
Crash when throwing any type of Bomb

### ISSUE THREAD

**Issue by Kutzeee** [Electroblob77/Wizardry#195] opened 2019-08-20 18:27 UTC
Minecraft version: 1.12.2 
Wizardry version: 4.2.1
Environment: Singleplayer

Issue details: Throwing any type of Bomb will crash the game

Link to crash report (if applicable): https://paste.dimdev.org/qeyivekobu.mccrash

**Comment by Electroblob77** [comment] 2019-08-20 19:09
Duplicate of #191.

**Closed as completed by Electroblob77** 2019-08-20 19:09 UTC
Labels: bug, duplicate
