### ISSUE TITLE
Crash: Going in range of a Shrine crashed the game.

### ISSUE THREAD

**Issue by SirAron111** [Electroblob77/Wizardry#203] opened 2019-08-21 20:01 UTC
Minecraft version: 1.12.2
Wizardry version: Electroblob's Wizardry - 4.2.1
Environment: Singleplayer

Issue details: Going in range of a Shrine crashed the game.
Ok I fought like 3 shrines and they worked great but the 4 I found crashed me the moment I got close to it.
Also on a side note the little obelisks with the spawners should have a guaranteed chance for one of the big elemental crystals like the shrines have a guaranteed chance to get a trinket. Because right now I mined like 8 obelisks got like one elemental crystal (one I didn’t even want for healing).

Link to crash report (if applicable):
https://pastebin.com/sjpZ2rmk

**Comment by Electroblob77** [comment] 2019-09-02 13:12
Not sure what's happened there, as far as I can tell nothing on that line can possibly be null. I'll have to look into it a bit further. Elemental crystals do generate in other chests too, but I might increase the chance a bit in obelisks

**Comment by Electroblob77** [comment] 2019-09-04 12:10
On further inspection, this is a duplicate of #185.

**Closed as completed by Electroblob77** 2019-09-04 12:10 UTC
Labels: bug, duplicate, crash
