### ISSUE TITLE
Should I be worried? Advancement spam, possible fps hit?

### ISSUE THREAD

**Issue by dazadazu** [Electroblob77/Wizardry#643] opened 2021-03-17 00:07 UTC
https://gyazo.com/8c54b6f70b0edb3fe60af45fb1438934

Its a pic

**Comment by Electroblob77** [comment] 2021-06-14 17:17
Duplicate of #475. If everything still works, then don't worry too much. However, it may cause some network lag. I'm still unsure as to why this happens, but advancement updates seem to get triggered repeatedly somehow.

**Closed as completed by Electroblob77** 2021-06-14 17:17 UTC
Labels: duplicate, question
