### ISSUE TITLE
Game crashed when using flame ray.  version 4.2.2 1.12.2 forge 14.23.5.2844

### ISSUE THREAD

**Issue by Sageking10** [Electroblob77/Wizardry#239] opened 2019-09-05 23:35 UTC
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.2 [change as necessary]
Environment: Singleplayer

Issue details: I used flame ray and the game crashed

https://paste.dimdev.org/nidelisifi.mccrash

**Comment by bigenergy** [comment] 2019-09-06 13:41
+1
I get the same error if I go into the sound settings

**Comment by bigenergy** [comment] 2019-09-07 11:54
@Electroblob77 pls fix this

**Comment by Electroblob77** [comment] 2019-09-08 22:37
Duplicate of #238

**Closed as completed by Electroblob77** 2019-09-08 22:37 UTC
Labels: bug, duplicate
