### ISSUE TITLE
Spirit Horse does not despawn in unloaded chunks

### ISSUE THREAD

**Issue by Minothilos** [Electroblob77/Wizardry#119] opened 2019-03-08 14:34 UTC
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: Singleplayer

Issue details: I'm playing on a singleplayer world where I spend a lot of time exploring to find new spells and other EBWizardry items. I'm using the home command from FTB Utility to teleport between my base and where I'm exploring. Right before I stopped playing yexterday I got of my horse, set a new home and teleported to my base. When I started playing this morning I was unable to summon my spirit horse. I had just updated three mods, including FTB Utility (although I doubt this is relevant) and thought that something in those updates could have caused the problem. I started up a new world where I could spawn a horse without problem (to my surprise) but could also replicate the issue by traveling a fair distance, summoning a horse and then teleporting back to spawn. The same issue occurs when summoning a horse and then using the Transportation spell to travel far enough to unload the chunks, which tells me it's an internal issue and isn't caused by other mods.

**Comment by Electroblob77** [comment] 2019-03-20 23:23
Duplicate of #74, thanks for the extra information though.

**Closed as completed by Electroblob77** 2019-03-20 23:23 UTC
Labels: duplicate
