### ISSUE TITLE
Arcane Workbench doesn't work

### ISSUE THREAD

**Issue by HiddenByNight** [Electroblob77/Wizardry#634] opened 2021-02-27 17:57 UTC
Minecraft version: 1.12.2 
Wizardry version: 4.3.4
Environment: Server 

This is similar to the issue with CompatSkills, except it happens even when no other mods are installed. The arcane workbench works fine in singleplayer, but when I try to use it in my forge server, nothing happens. The animation and sound effect plays, but the wand doesn't receive spells or mana. I tried with different versions of Forge (14.23.5.2838 and 14.23.5.2854), as wells as different versions of EBW (4.3.4, 4.2.11, 4.2.10, 4.2.0, 4.1.0). I've been told on the Discord server that the log files have nothing relevant in them but I'll post them anyways.

Client log: 
[latest.log](https://github.com/Electroblob77/Wizardry/files/6055025/latest.log)
Client debug log:
[debug.log](https://github.com/Electroblob77/Wizardry/files/6055026/debug.log)
Server log:
[latest.log](https://github.com/Electroblob77/Wizardry/files/6055031/latest.log)
Server debug log:
[debug.log](https://github.com/Electroblob77/Wizardry/files/6055032/debug.log)

**Comment by Electroblob77** [comment] 2021-06-18 17:07
Ran a local server in my dev environment (Forge 14.23.5.2487, Wizardry 4.3.4), logged in and the arcane workbench works just fine in survival and creative. Can't see anything out of the ordinary in those logs either. All I can suggest is doing a completely fresh server installation in a clean folder, let it generate a new world and see if that changes anything.

**Comment by 3omar13** [comment] 2021-07-11 19:55
I have the same problem but restarting is not an option

**Comment by WinDanesz** [comment] 2022-02-03 13:54
Duplicate of #609

**Closed as completed by WinDanesz** 2022-02-03 13:54 UTC
Labels: bug, can't reproduce
