### ISSUE TITLE
Client Game Crash on Spell Cast - Sound Event Related Error, Array Index Exception

### ISSUE THREAD

**Issue by timeherald** [Electroblob77/Wizardry#241] opened 2019-09-07 22:16 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.2 
Environment: Server, multiplayer

Issue details: I cast the speed time spell, and the game crashed, with tons of error screens, all with the same error. The server stays up, so it's definitely a client-related error on the part of Wizardry, since this crash was not happening before I updated. 

Here's a couple of lines from the error: 

Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 12
    at java.util.EnumMap.containsKey(EnumMap.java:222)
    at net.minecraft.client.settings.GameSettings.getSoundLevel(GameSettings.java:1578)
    at net.minecraft.client.audio.SoundManager.getVolume(SoundManager.java:160)
    at net.minecraft.client.audio.SoundManager.getClampedVolume(SoundManager.java:451)
    at net.minecraft.client.audio.SoundManager.playSound(SoundManager.java:401)
    at net.minecraft.client.audio.SoundHandler.playSound(SoundHandler.java:258)
    at electroblob.wizardry.client.audio.SoundLoop.update(SoundLoop.java:49)
    at electroblob.wizardry.client.audio.SoundLoopSpell.update(SoundLoopSpell.java:32)
    at electroblob.wizardry.client.audio.SoundLoop$$Lambda$3493/532172108.accept(Unknown Source)
    at java.lang.Iterable.forEach(Iterable.java:75)

Here's a full link to the crash report: https://paste.dimdev.org/ojepajubos.mccrash

**Comment by Electroblob77** [comment] 2019-09-08 22:35
Duplicate of #238

**Closed as completed by Electroblob77** 2019-09-08 22:35 UTC
Labels: bug, duplicate
