### ISSUE TITLE
Player rendering crash

### ISSUE THREAD

**Issue by rwja16** [Electroblob77/Wizardry#549] opened 2020-11-09 13:15 UTC
Minecraft version: 1.12.2 
Wizardry version: 4.3.1 
Environment: Singleplayer

Issue details: Crashed when I pressed F5 on my world, and now it crashes every time I try to enter any world.

Other mods involved: many 

Link to crash report: [pastebin](https://pastebin.com/RkCVgvuz)

**Comment by Electroblob77** [comment] 2020-12-04 19:17
Duplicate of #551.

**Closed as completed by Electroblob77** 2020-12-04 19:17 UTC
Labels: bug, duplicate
