### ISSUE TITLE
A mod has called ItemScroll#getItemStackDisplayName from the server side

### ISSUE THREAD

**Issue by flamechair** [Electroblob77/Wizardry#62] opened 2018-08-01 17:03 UTC
Minecraft version: 1.12.2  
Wizardry version: 4.1.2 [change as necessary]  
Environment: Server [delete as necessary]

Issue details: on boot up this is present several times in the server log:
```
> [16:37:32] [Server thread/INFO] [ebwizardry]: A mod has called ItemScroll#getItemStackDisplayName from the server side. Using thedeprecated server-side translation methods as a fallback.
> [16:37:32] [Server thread/INFO] [ebwizardry]: A mod has called ItemScroll#getItemStackDisplayName from the server side. Using thedeprecated server-side translation methods as a fallback.
> [16:37:32] [Server thread/INFO] [ebwizardry]: A mod has called ItemScroll#getItemStackDisplayName from the server side. Using thedeprecated server-side translation methods as a fallback.
```

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by Electroblob77** [comment] 2018-08-01 21:30
This is a duplicate of #56. Please check if your issue has been posted before in future! Thanks.

**Closed as completed** 2018-08-01 21:30 UTC
Labels: duplicate
