### ISSUE TITLE
Player Summoned Mobs lose Ownership when Entering/Leaving the End Dimension

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#21] opened 2018-04-30 23:13 UTC
Minecraft version: 1.12.2
Wizardry version: 4.1.1
Environment: All (Single/Multiplayer)

Issue details: 
Apparently, If you or your summon tries to enter the End dimension, The Summons are no longer considered to be owned by you. Resulting them attacking you as if a evil wizard summoned it instead of you.

Their names are also affected, It no longer says 'PlayerName's Summon', but just says the original mob's Name.

Steps to Repeat:
------------------

1. Get a wand with a Summon Mob Spell or a Summon Mob Scroll.
2. Cast the Summon Spell. (It can be any mob, so as long it doesn't fly.)
3. Spawn an End Portal using this command cus it's faster: /fill ~ ~ ~ ~ ~ ~ end_portal
4. Proceed to push your summoned Mob the End Dimension Portal. **[Or you can do Step 5 instead]** (You can also use whirlwind or just let it walk into the portal)
5. Walk into the End Dimension Portal.
5. Let the Game load the End Dimension.
6. Go back to the Overworld. (If you did step 4, skip this step)
7. Find your Previous Summoned Mob, it will attack you and lose it's Ownership Tag.

------------------

They will still despawn after 30 seconds like normal.

**This bug isn't really a big deal (Cause the fact that leaving and Entering the End Dimension is coded really funny), but i'm just gonna point this oddity out.**

Other mods involved: None

**Comment by Electroblob77** [comment] 2018-05-01 15:33
Ok, I must have missed this because it's so obscure. Does it happen with nether portals as well? Either way, I'll get it fixed in the next patch.

**Comment by Ghostrider231** [comment] 2018-05-01 19:21
no, I've tested other Dimensions including the nether portal and it doesn't have this bug.

**Comment by Electroblob77** [comment] 2018-06-04 16:55
I can confirm this is happening, although strangely the creature retains its nameplate saying who summoned it.

**Comment by Electroblob77** [comment] 2019-08-18 12:23
Fixed in the 4.2.0 release.

**Closed as completed by Electroblob77** 2019-08-18 12:23 UTC
Labels: bug, low priority
