### ISSUE TITLE
Error Executing Task

### ISSUE THREAD

**Issue by DrevianAlexander** [Electroblob77/Wizardry#332] opened 2019-12-30 08:20 UTC
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.2.7
Environment: Singleplayer

Issue details: Issue presents at loading world. Appears to result in the inability to modify wands.

Other mods involved: Mc.Eternal modpack, but I dont know if any specific mod is interacting.

Link to crash report (if applicable): https://paste.dimdev.org/abopeyapoz.mccrash

[crash-2019-12-30_01.14.17-client.txt](https://github.com/Electroblob77/Wizardry/files/4009275/crash-2019-12-30_01.14.17-client.txt)

**Comment by Electroblob77** [comment] 2019-12-31 11:00
Looks like a duplicate of #253. This is a bug in the arcane essentials addon.

**Closed as completed by Electroblob77** 2019-12-31 11:00 UTC
Labels: duplicate, crash, external bug
