### ISSUE TITLE
Mind Control crash with Rough Mobs 2

### ISSUE THREAD

**Issue by Luke616** [Electroblob77/Wizardry#106] opened 2019-01-08 20:29 UTC
Versions:
Minecraft version: 1.12.2 
Wizardry version: 4.1.4
Forge: 14.23.5.2796
Environment: Server

Issue details: Unsure if this issue would needs to be fixed on your end of theirs - if a mob from rough mobs 2 is mind controlled and then attacked by its allied player, the client and server will both crash.

Other mods involved:
Rough Mobs 2: 2.0.11

Link to crash report:
This is the initial crash
https://pastebin.com/7UYFHgJH

This is a crash that happens when you attempt to start the server back up
https://pastebin.com/xNbtS860

Thanks!

**Comment by Electroblob77** [comment] 2019-01-11 18:05
Though on the surface it seems different, this is actually the same root issue as #72, caused by cross-mod infinite looping in attack events. I've implemented a fix in my dev branch so this will be fixed in the next update.

**Closed as completed by Electroblob77** 2019-01-11 18:05 UTC
Labels: duplicate
