### ISSUE TITLE
Embers Rekindled particles are white with EB Wizardry

### ISSUE THREAD

**Issue by Circine** [Electroblob77/Wizardry#208] opened 2019-08-22 19:20 UTC
Minecraft version: 1.12.2
Wizardry version: 4.2.1

Issue details: Ember particles from machines turn white when EB Wizardry is added. I disabled custom shaders from Wizardry to see if that was the cause, but it still happens. Everything still functions, so this is just a cosmetic bug.
Picture:(top is normal, bottom is with Wizardry)
https://i.imgur.com/9gMTuyk.jpg

Other mods involved: Embers Rekindled

**Comment by Electroblob77** [comment] 2019-09-02 13:56
I think this might be related to #170.

**Comment by SirAron111** [comment] 2019-09-03 22:22
Yes seems to relate to #170. I have the same problem with embers i think i saw it on botania to would need to check it again something in ebwiz does strange things to certain overlays and effects.

**Comment by SirAron111** [comment] 2019-09-12 15:37
Even in version 4.2.3 ...Mmm looks like a few more mods show issues with particles like draconic evolution turning from its blue and orange particles on the infusion crafter to pure gray balls. or the astral sorcery particles and rendering from things like illumination wands turns gray as well i think its related to the same reason the embers particles are turned Gray/White or the neat plats turning gray etc. i think something in ebwiz messes up particles be it rendered in world or rendered on client only. you should give this issue a priority boost, since its not really just cosmetic at this point and also could be a more heavy affect or error for GPU usage since some players reported a huge spike in gpu usage when one of the color corrupted particles trys to render.

Since the neat plates were very specific and seemed to only happen when combined with psi but he embers one and the ones like draconic/astral seem to also happen without it, I posted it here. But I think it’s definitely related or at least affected by the same root cause like the sound category was for the sound bug.

And probably because there is an incompatibility with mods that activate custom shaders/particle or anything like that by default maybe you are in some way blocking other mods shades or renderers unintentionally. Since neat and psi run on the same library autoreglib I think when psi gets activated it triggers a part of the code that uses a custom shader and the moment that gets blocked by ebwiz it affects the plates as well as they suddenly can’t access this feature anymore. And it just happens to mods like embers etc by default as such a code part is activated on them by default to render their stuff.

If you can’t reproduce it I can offer you to simply download my modpack “Dimension Zero” version 9.1 which contains the new EBWiz and all these conflicting mods that show these issues at once and you will be 100% sure to trigger these problems listed here. (Thought I removed “neat” but that’s easy to add.) Maybe that will help you find the bug.

here a picture of the gray glow orbs from ilumination wand (normally yellow) the gray circle of particles from draconic (normally blue red) and blank embers.

![2019-09-12_18 50 10](https://user-images.githubusercontent.com/39855956/64804003-4cad2a00-d58e-11e9-8eec-a5f1f091a35c.png)

More overlays also seems to be affected losing all color turning blank
![2019-09-12_20 27 05](https://user-images.githubusercontent.com/39855956/64810615-f7781500-d59b-11e9-998d-6f8b51d398e0.png)

**Comment by SirAron111** [comment] 2019-09-16 17:07
Found another thing that seems to be getting a few issues with the new EBWiz visually. Thought this only happened server side. The Between lands mod Boss Primordial Melovelances Projectiles turn invisible. Making it hard (nearly impossible) to hit back the green colored one…. Maybe you should make sure your effects/shaders and everything only applies to your spells. Maybe you are accessing and or overwriting some graphic effects needed by other things.

**Comment by MokahTGS** [comment] 2019-11-15 18:53
We are having an issue with More Overlays and getting all grey x's which people are seeing the same thing over there.

**Comment by Electroblob77** [comment] 2020-01-12 15:07
Should be fixed by PR #319 (released in version 4.2.6). Please reopen if the issue persists.

**Closed as completed by Electroblob77** 2020-01-12 15:07 UTC
Labels: bug, cosmetic

**Comment by talonos2** [comment] 2020-05-15 23:33
Persists for me. I even tried backing up to 4.2.6 to see if that version worked for me, and it did not.

Has it worked for anybody else? If so, what combination of mods did it work for you with?

**Comment by talonos2** [comment] 2020-05-16 20:38
Found it. Cross mod interaction three ways: Can only duplicate with Thaumic Tinkerer, Electroblob's Wizardry, and Embers all installed together.

Weird.
